Elaborating on SetShardTabletControl
vitessio/website pull request #1009
Opened 2022-04-08 23:11 UTC by FancyFane

Signed-off-by: FancyFane <fane@planetscale.com>

Changes made to v14 in draft mode; once validated we can work on replicating changes to other versions. 

- Added in links to relevant commands
- Added in additional examples as usage and behavior can be ambiguous
- Added note to run `RefreshStateByShard` after making modifications
- Updated terms to reflect terminology used in the topology record

2022-04-11 15:37 UTC, Anders-PlanetScale requested changes

2022-04-11 15:37 UTC, Anders-PlanetScale commented on content/en/docs/14.0/reference/programs/vtctl/shards.md
> +Sets the shardTabletControls record for a shard and tablet type in the topology service. Only use this for an emergency fix or after a finished vertical split or after a corrupted MoveTables action.
Replace shardTabletCrontrols with ShardTabletControl

2022-04-11 15:37 UTC, Anders-PlanetScale commented on content/en/docs/14.0/reference/programs/vtctl/shards.md
> +To set the queryServiceDisabled, set `disable_query_service` to true; to unset the queryServiceDisabled provide `denied_tables` with an empty tablet set. Useful to fix vReplication operations gone wr
Maybe note that `disable_query_service=false` does not do anything, instead you need to provide denied_tables with an empty table set.

Also fix tablet set, to table set

2022-04-11 15:44 UTC, FancyFane commented on content/en/docs/14.0/reference/programs/vtctl/shards.md
> +Sets the shardTabletControls record for a shard and tablet type in the topology service. Only use this for an emergency fix or after a finished vertical split or after a corrupted MoveTables action.
Taking a look at this we may want to add the "s" to the end everywhere `ShardTabletControl` appears. The reasoning is this is the way it's defined in the topology service:

```sh
vtctlclient SetShardTabletControl -- --disable_query_service=true commerce/0 primary
vtctlclient TopoCat -- --cell zone1 --decode_proto_json  /keyspaces/commerce/SrvKeyspace  | jq .
```

```json
...
        "shardTabletControls": [
          {
            "name": "0",
            "queryServiceDisabled": true
          }
        ]
```

2022-04-11 16:00 UTC, Anders-PlanetScale commented on content/en/docs/14.0/reference/programs/vtctl/shards.md
> +Sets the shardTabletControls record for a shard and tablet type in the topology service. Only use this for an emergency fix or after a finished vertical split or after a corrupted MoveTables action.
OK, yeah then we need to make sure we use shardTabletControls when discussing the topo record, and `SetShardTabletControl` when discussing the vtctl command.

2022-04-12 00:46 UTC, FancyFane commented on content/en/docs/14.0/reference/programs/vtctl/shards.md
> +Sets the shardTabletControls record for a shard and tablet type in the topology service. Only use this for an emergency fix or after a finished vertical split or after a corrupted MoveTables action.
I've added additional clarification and copy/pasted they keys names in the topology server for each of these changes.

2022-04-12 00:47 UTC, FancyFane commented on content/en/docs/14.0/reference/programs/vtctl/shards.md
> +To set the queryServiceDisabled, set `disable_query_service` to true; to unset the queryServiceDisabled provide `denied_tables` with an empty tablet set. Useful to fix vReplication operations gone wr
I've fixed tablet set to read table set; I've added a warning with the note about `disable-query_service=false`.

2022-04-26 19:02 UTC, Anders-PlanetScale approved these changes

2022-04-26 21:18 UTC, FancyFane commented
- Removed double dash in v13, v12, and v11
- Corrected flags and topology variables in v12 and v11 which use outdated language

2022-04-26 21:26 UTC, Anders-PlanetScale approved these changes
LGTM

2022-04-26 21:27 UTC, merged