made changes to navbar, footer
vitessio/website pull request #1117
Opened 2022-07-27 17:59 UTC by reveurguy

Signed-off-by: reveurguy <59417546+reveurguy@users.noreply.github.com>

- Added background to hero,footer. 
- made changes to navbar style
- updated fontawesome version

2022-07-28 09:54 UTC, GuptaManan100 commented
@reveurguy If you were doing the open-close draft-ready for getting the CI to run, then that is not required. For external contributors, netlify requires an approval from a member to run the preview

2022-07-28 09:57 UTC, GuptaManan100 reviewed
I like the changes but I am not sure why we have removed the `yarn.lock` file. I'll let someone with more web experience have the final word.

2022-07-28 10:16 UTC, reveurguy commented
> @reveurguy If you were doing the open-close draft-ready for getting the CI to run, then that is not required. For external contributors, netlify requires approval from a member to run the preview. I just approved it, so they'll run now.

ok, yeah i was doing that for that only😅

2022-07-28 10:17 UTC, reveurguy commented
> I like the changes but I am not sure why we have removed the `yarn.lock` file. I'll let someone with more web experience have the final word.

that was updated automatically, when i ran the site locally

2022-07-28 14:40 UTC, deepthi commented
@reveurguy can you attach before and after screenshots? Alternatively, you can link to the specific changed pages in the preview.
For instance, I can see that you have changed the background on the homepage, but I can't tell what else has changed.

2022-07-28 14:54 UTC, deepthi commented
@nate-double-u @chalin can one of you review the changes? the diff on `yarn.lock` is huge.

2022-07-28 15:31 UTC, reveurguy commented
# Before

<img width="1375" alt="Screenshot 2022-07-28 at 8 57 32 PM" src="https://user-images.githubusercontent.com/59417546/181576995-e4d99c99-f619-4e13-a494-91ecb0c91df5.png">

# After
<img width="1380" alt="Screenshot 2022-07-28 at 8 57 18 PM" src="https://user-images.githubusercontent.com/59417546/181576944-0324a83f-00de-4b60-8328-4b9ba2c4f53d.png">

# before 
<img width="1382" alt="Screenshot 2022-07-28 at 8 58 49 PM" src="https://user-images.githubusercontent.com/59417546/181577280-d1e8aa5e-8f35-47cf-a300-c616ee0f6016.png">

# after
<img width="1379" alt="Screenshot 2022-07-28 at 8 58 34 PM" src="https://user-images.githubusercontent.com/59417546/181577232-eb8c3fc2-6d16-4944-aea4-171088f578f4.png">

2022-07-28 15:31 UTC, reveurguy commented
initially i have made these small changes only.

2022-07-28 16:17 UTC, deepthi commented
@reveurguy can you look at this on mobile? The changes to the button shapes mean that they look kind of awkward now.
![File](https://user-images.githubusercontent.com/388311/181587714-b7462e9b-c512-4bc6-93f9-08a03e231468.jpg)

2022-07-28 16:56 UTC, chalin commented
> @nate-double-u @chalin can one of you review the changes? the diff on `yarn.lock` is huge.

My suggestion is to drop the lock file from version control:

- #1106

2022-07-28 17:03 UTC, chalin commented
I'd suggest leaving the footer the way it was. The new styling would make the text difficult to read for some. My 2 cents.

2022-07-28 17:04 UTC, chalin commented
@thisisobate - any comments about the suggested changes?

2022-07-28 21:13 UTC, nate-double-u commented
> My suggestion is to drop the lock file from version control:

+1

2022-07-30 03:57 UTC, thisisobate requested changes
+1 on the lock file as @nate-double-u and @chalin suggested.

Add a background image to the footer or leave it as it was before? either way works tbh.

@reveurguy If you want to go with the former, then you should fix the readability issues @chalin mentioned.

2022-07-30 03:57 UTC, thisisobate commented on layouts/partials/footer.html
> +    <hr class="has-background-black">
revert the `hr` color back to orange as the black foreground doesn't match with the background image

2022-07-30 03:57 UTC, thisisobate commented on layouts/partials/footer.html
>      <nav class="level">
The Nav color doesn't match well with the background; can barely read the text. I think you should use a text color that has good color contrast and matches the background- white is a good candidate.

2022-07-30 03:57 UTC, thisisobate commented on layouts/partials/footer.html
>      <nav class="level">
Also, the external link's contrast isn't great. You should increase it (very light blue color might do the trick?)

2022-07-30 04:00 UTC, thisisobate commented on layouts/partials/footer.html
> +    <hr class="has-background-black">
<img width="1697" alt="Screenshot 2022-07-30 at 04 58 58" src="https://user-images.githubusercontent.com/29557702/181871589-3043e76b-502f-4fc0-9e3a-5605469ba949.png">

The Nav color doesn't match well with the background; can barely read the text. I think you should use a text color that has good color contrast and matches the background- white is a good candidate.

2022-07-30 04:00 UTC, thisisobate commented on layouts/partials/footer.html
> +    <hr class="has-background-black">
Also, the external link's contrast isn't great. You should increase it (very light blue color might do the trick?)

2022-07-31 15:42 UTC, reveurguy commented
made the  required changes

2022-08-01 16:23 UTC, deepthi approved these changes
Looks like all reviews have been addressed.
Re `yarn.lock`, more changes are required to drop `yarn` completely but they can be done separately whenever someone picks up #1106

2022-08-01 16:24 UTC, merged