Documenting vreplication flag: vreplication_max_time_to_retry_on_error
vitessio/website pull request #1136
Opened 2022-08-18 06:33 UTC by shlomi-noach

This PR documents the flag `--vreplication_max_time_to_retry_on_error`, introduced in https://github.com/vitessio/vitess/pull/10429. The default for this flag is modified in https://github.com/vitessio/vitess/pull/11031. https://github.com/vitessio/vitess/pull/11031 is expected to be backported to v14, and so this PR updates both `v15` and `v14`.

Related:
- https://github.com/vitessio/vitess/pull/11031
- https://github.com/vitessio/vitess/issues/10783

2022-08-18 16:09 UTC, mattlord approved these changes
Had one minor suggestion, but looks good!

2022-08-18 16:09 UTC, mattlord commented on content/en/docs/15.0/reference/vreplication/flags.md
> +**Default** 0\
IMO, we could clarify here:
```
**Default** 0 (unlimited)\
```

2022-08-18 19:29 UTC, mattlord commented
@shlomi-noach one other not-required request here... I think it would be a good idea to add documentation on that flag here for v14 and v15: https://vitess.io/docs/15.0/reference/vreplication/flags/

Then we can expound on it too like what if any related status/metrics exist, when you may want to change the default and why, etc. 

If you don't want to do that then let me know and I'll create a ToDo for it.

2022-08-18 19:33 UTC, mattlord requested changes
This `--vreplication_max_time_to_retry_on_error` flag should also be listed on the `vttablet` flag reference pages:
  - https://vitess.io/docs/14.0/reference/programs/vttablet/
  - https://vitess.io/docs/15.0/reference/programs/vttablet/

Those pages should be a complete list of `vttablet` flags to matches the help output. Unfortunately that's not true today (e.g. some OnlineDDL related ones aren't there) but we should try our best to keep that in sync with the full flag set and help output.

Thank you! If you want, I'm more than happy to push commits to this PR for that part.

2022-08-21 05:33 UTC, shlomi-noach commented on content/en/docs/15.0/reference/vreplication/flags.md
> +**Default** 0\
done

2022-08-21 05:33 UTC, shlomi-noach commented
> This --vreplication_max_time_to_retry_on_error flag should also be listed on the vttablet flag reference pages:

Done!

2022-08-22 14:28 UTC, mattlord approved these changes
❤️

2022-08-23 05:59 UTC, merged