Document VStream
vitessio/website pull request #1216
Opened 2022-11-08 00:36 UTC by mattlord

And the new vstream copy resume work added in:
  https://github.com/vitessio/vitess/pull/11103

Signed-off-by: Matt Lord <mattalord@gmail.com>

2022-11-28 17:23 UTC, rohit-nayak-ps requested changes
Great, we have been missing such a doc for VStream ... 

Have suggested some changes/additions.

2022-11-28 17:23 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +[GoldenGate](https://docs.oracle.com/en/middleware/goldengate/core/21.3/gghdb/using-oracle-goldengate-mysql.html).
How would a user integrate with `GoldenGate`?

2022-11-28 17:23 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +    Gtid:     fmt.Sprintf("%s/%s", mpos.GTIDSet.Flavor(), mpos),
Can we just show a gtidset here instead of basing it on `mpos`? Or we show how `mpos` is obtained...

2022-11-28 17:23 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +
Do we want to talk about the MySQL interface? It is not really a VStream API functionality, it is hacky and has minimal use/support ... We also don't want anyone to start depending on it.

2022-11-28 17:23 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +reader, err := gconn.VStream(ctx, topodatapb.TabletType_PRIMARY, vgtid, filter, flags)
Have we documented the VStream flags elsewhere? (don't think so). If not, we can do it in this doc.

2022-12-07 08:21 UTC, rsajwani commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +{{< warning >}}
is it right markdown for warning.. Its not appearing correctly in preview.

2022-12-07 20:35 UTC, mattlord commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +{{< warning >}}
I'm not sure what you're looking at, but it's not markdown but rather a hugo/netlify syntax.

2022-12-27 21:37 UTC, mattlord commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +
I think it's useful for debugging/testings. That's why I only call it out in that section.

2022-12-27 21:48 UTC, mattlord commented
Just FYI, I'm going to try and finish this out tomorrow. I'll make some additions/changes based on @rohit-nayak-ps's feedback.

2022-12-27 21:51 UTC, mattlord commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +[GoldenGate](https://docs.oracle.com/en/middleware/goldengate/core/21.3/gghdb/using-oracle-goldengate-mysql.html).
It should work to some extent as GoldenGate supports MySQL as a source and sink (using binary logs). But probably not worth mentioning as it will likely not work properly in various ways. I'll remove it

2022-12-28 03:04 UTC, yoheimuta commented
> And the new vstream copy resume work added in:
https://github.com/vitessio/vitess/pull/11909

@mattlord Hi. As to https://github.com/vitessio/vitess/pull/11909#issuecomment-1350806126, is something missing in this request?
I was going to add the below commit.

<details>
<summary>commit</summary>

```diff
Commit: 241e00346d3bc7ce592b1d36f0d47389e92905b5 (HEAD -> vstream_docs)
Author: yoheimuta <yoheimuta@gmail.com>
Date:   2022-12-14 19:15:29 +0900 (2 weeks ago)

Add info about the new ability to copy all tables in a keyspace or all tables in all keyspaces. It's added in https://github.com/vitessio/vitess/pull/11909
---
 .../en/docs/16.0/reference/vreplication/vstream.md | 31 ++++++++++++++++++++++
 1 file changed, 31 insertions(+)

diff --git a/content/en/docs/16.0/reference/vreplication/vstream.md b/content/en/docs/16.0/reference/vreplication/vstream.md
index 5f714c74..95a9f6d8 100644
--- a/content/en/docs/16.0/reference/vreplication/vstream.md
+++ b/content/en/docs/16.0/reference/vreplication/vstream.md
@@ -97,6 +97,37 @@ for {
     ...
 
+### Copy all tables in a keyspace
+```
+vgtid := &binlogdatapb.VGtid{
+  ShardGtids: []*binlogdatapb.ShardGtid{{
+    Keyspace: "ks",
+    Gtid: "",
+  }},
+}
+filter := &binlogdatapb.Filter{
+  Rules: []*binlogdatapb.Rule{{
+    Match: "/.*/",
+  }},
+}
+reader, err := gconn.VStream(ctx, topodatapb.TabletType_PRIMARY, vgtid, filter, flags)
+```
+
+### Copy all tables in all keyspaces
+```
+vgtid := &binlogdatapb.VGtid{
+  ShardGtids: []*binlogdatapb.ShardGtid{{
+    Gtid: "",
+  }},
+}
+filter := &binlogdatapb.Filter{
+  Rules: []*binlogdatapb.Rule{{
+    Match: "/.*/",
+  }},
+}
+reader, err := gconn.VStream(ctx, topodatapb.TabletType_PRIMARY, vgtid, filter, flags)
+```
+
 ## Debugging
 
 There is also an SQL interface that can be used for testing and debugging from a `vtgate`. Here's an example:
```
</details>

2022-12-28 16:55 UTC, mattlord commented
> > And the new vstream copy resume work added in:
> > [vitessio/vitess#11909](https://github.com/vitessio/vitess/pull/11909)
> 
> @mattlord Hi. As to [vitessio/vitess#11909 (comment)](https://github.com/vitessio/vitess/pull/11909#issuecomment-1350806126), is something missing in this request? I was going to add the below commit.

@yoheimuta I've added you as a collaborator on the website repo so you should be able to open PRs directly against the repo and push commits to PRs like this one. In this specific case though... I'm not 100% sure that will be the final syntax but I think it probably will. Our options are to include it in this one or do it separately. At this point it's a matter of timing: if the PR gets approved before this is merged then makes sense to include it. If not, then we can do it in a separate PR.

Thanks!

2023-01-04 23:57 UTC, rsajwani commented on content/en/docs/16.0/reference/vreplication/vstream.md
> +{{< warning >}}
i verified it doesn't show up in review mode. I think we are good here.

2023-01-05 00:03 UTC, rsajwani approved these changes

2023-01-07 19:42 UTC, rohit-nayak-ps approved these changes
lgtm

2023-01-07 19:44 UTC, rohit-nayak-ps commented
@mattlord, since https://github.com/vitessio/vitess/pull/11909 is still in progress, maybe we can remove it from the description and merge this now and document it in a separate PR.

2023-01-07 19:56 UTC, mattlord commented
> @mattlord, since [vitessio/vitess#11909](https://github.com/vitessio/vitess/pull/11909) is still in progress, maybe we can remove it from the description and merge this now and document it in a separate PR.

Sounds good. I'll remove it from the description here and we'll do a follow-up. Thanks!

2023-01-07 19:57 UTC, merged