Update VReplication Reference Pages
vitessio/website pull request #1267
Opened 2022-11-30 16:51 UTC by mattlord

Documents: https://github.com/vitessio/vitess/pull/11705
Fixes: https://github.com/vitessio/website/issues/1242

2022-12-06 23:36 UTC, mattlord commented on content/en/docs/16.0/user-guides/migration/cutover.md
> +Note that running VDiff via vtctld can lead to vtctld consuming significantly more memory than usual.
Copying this relevant comment over: https://github.com/vitessio/website/pull/1187/files#r1002133833

2022-12-14 13:57 UTC, rohit-nayak-ps requested changes
Nice! 

Noticed a few minor issues. Otherwise looks very good.

2022-12-14 13:57 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/metrics.md
> +VReplication exports several metrics using the expvars interface. These are available at the `/debug/vars` endpoint of vttablet's http status pages. [More details can be found here](../../features/mo
The anchor is repeated and hence link doesn't work as expected.

2022-12-14 13:57 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/movetables.md
> +will stop once the copy is done and you can then mark the workflow as `Complete`d
`Complete`d doesn't render well, probably best to remove the trailingd.

2022-12-14 13:57 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/movetables.md
> +###### Uses
Incorrect cut/paste: this is the same text as for `auto_start`

2022-12-14 13:57 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/reshard.md
> +* allows updating the rows in `_vt.vreplication` after `Reshard` has setup the
Same issue here as in MoveTables. Need to change this text.

2022-12-20 19:49 UTC, mattlord commented
Thanks, @rohit-nayak-ps ! I believe that I addressed your comments here: https://github.com/vitessio/website/pull/1267/commits/e02d88c52b943f2f15e87fb90e8516958c1baa1e

2022-12-22 05:40 UTC, harshit-gangal approved these changes

2022-12-22 10:03 UTC, rohit-nayak-ps requested changes

2022-12-22 10:03 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/tablet_selection.md
> +For both [VTGate VStreams and VTTablet VReplication streams](../../../concepts/vstream/) we must choose a tablet to serve the role of source (vstreamer). For VReplication streams we must also choose
We don't choose a target tablet: vreplication streams are running on the target shard's primary.

2022-12-22 10:03 UTC, rohit-nayak-ps commented on content/en/docs/16.0/reference/vreplication/tablet_selection.md
> +The `TabletPicker` will only look for source and target tablet tablets within the same cell of the calling process by default — the `vtgate` managing the VStream or the target `vttablet` for a VRepli
typo: "tablet tablets"

2022-12-22 16:47 UTC, mattlord commented on content/en/docs/16.0/reference/vreplication/tablet_selection.md
> +For both [VTGate VStreams and VTTablet VReplication streams](../../../concepts/vstream/) we must choose a tablet to serve the role of source (vstreamer). For VReplication streams we must also choose
Good catch! Mistake in modifying that paragraph. I've cleaned it up here: https://github.com/vitessio/website/pull/1267/commits/e4696ec3fbe3ac4ace100d4ce919331cc0535af3

2022-12-22 16:51 UTC, rohit-nayak-ps approved these changes

2022-12-22 17:05 UTC, merged