V15 fix links
vitessio/website pull request #1359
Opened 2023-01-25 16:28 UTC by dogukanteber

Partly fixes #1171. Some links are temporarily skipped due to the absence of `VStream API` page in v15. Below is the result of `make check-internal-links` command:

```
dogukan@dogukan:~/website$ make check-internal-links | grep 15.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10278  100 10278    0     0   5868      0  0:00:01  0:00:01 --:--:--  5866
wjdp/htmltest info checking GitHub for latest tag
wjdp/htmltest info found version: 0.17.0 for v0.17.0/linux/amd64
wjdp/htmltest info installed ./bin/htmltest
15.0/reference/vreplication/internal/vstream-stream-migration/index.html
  target does not exist --- 15.0/reference/vreplication/internal/vstream-stream-migration/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/vstream-stream-migration/index.html --> ../../vstream/
15.0/reference/vreplication/internal/life-of-a-stream/index.html
  target does not exist --- 15.0/reference/vreplication/internal/life-of-a-stream/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/life-of-a-stream/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/life-of-a-stream/index.html --> ../../vstream/
15.0/reference/vreplication/internal/vstream-skew-detection/index.html
  target does not exist --- 15.0/reference/vreplication/internal/vstream-skew-detection/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/vstream-skew-detection/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/vstream-skew-detection/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/vstream-skew-detection/index.html --> ../../vstream/#minimizeskew
  target does not exist --- 15.0/reference/vreplication/internal/vstream-skew-detection/index.html --> ../../vstream/
  target does not exist --- 15.0/reference/vreplication/internal/vstream-skew-detection/index.html --> ../../vstream/
253 errors in 1580 documents
make: *** [Makefile:37: run-link-checker] Error 1
```
This PR will be updated when it is decided how to replace `VStream API` file.

2023-01-25 17:01 UTC, mattlord commented
Thanks, @dogukanteber ! ❤️

2023-01-25 19:39 UTC, mattlord reviewed
There were a few links that I'm not sure about, but everything else looks good (I double checked the links on each page in the netlify preview). Thank you again!

2023-01-25 19:39 UTC, mattlord commented on content/en/docs/15.0/reference/features/vindexes.md
> +Consistent lookup vindexes use an alternate approach that makes use of careful locking and transaction sequences to guarantee consistency without using 2PC. This gives the best of both worlds, with t
This should go directly to the RFC in GitHub now: https://github.com/vitessio/vitess/issues/4855

2023-01-25 19:39 UTC, mattlord commented on content/en/docs/15.0/user-guides/schema-changes/managed-online-schema-changes.md
> +  - `DROP TABLE` statements run [safely and lazily](https://github.com/vitessio/vitess/blob/main/doc/design-docs/SafeLazyDropTables.md).
I'm not sure if this is right now not. @deepthi, do you know?

2023-01-25 19:39 UTC, mattlord commented on content/en/docs/15.0/user-guides/schema-changes/managed-online-schema-changes.md
> +For more about internals of the scheduler and how migration states are controlled, see [Online DDL Scheduler](https://github.com/vitessio/vitess/blob/main/doc/design-docs/OnlineDDLScheduler.md)
I'm also not sure if this is right or not. @deepthi or @shlomi-noach ? Note that this link is corrected in quite a few pages here.

2023-01-25 19:56 UTC, mattlord commented on content/en/docs/15.0/user-guides/schema-changes/managed-online-schema-changes.md
> +  - `DROP TABLE` statements run [safely and lazily](https://github.com/vitessio/vitess/blob/main/doc/design-docs/SafeLazyDropTables.md).
I confirmed that it's what we're now using here: https://vitess.io/docs/design-docs/online-ddl/

So we're good!

2023-01-25 19:57 UTC, mattlord commented on content/en/docs/15.0/user-guides/schema-changes/managed-online-schema-changes.md
> +For more about internals of the scheduler and how migration states are controlled, see [Online DDL Scheduler](https://github.com/vitessio/vitess/blob/main/doc/design-docs/OnlineDDLScheduler.md)
I confirmed that it's what we're now using here: https://vitess.io/docs/design-docs/online-ddl/

So we're good!

2023-01-25 19:57 UTC, mattlord approved these changes

2023-01-25 19:58 UTC, mattlord requested changes

2023-01-25 19:58 UTC, mattlord commented on content/en/docs/15.0/reference/features/vindexes.md
> +Consistent lookup vindexes use an alternate approach that makes use of careful locking and transaction sequences to guarantee consistency without using 2PC. This gives the best of both worlds, with t
This is the only thing to fix now.

2023-01-26 13:08 UTC, frouioui commented on content/en/docs/15.0/reference/features/vindexes.md
> +Consistent lookup vindexes use an alternate approach that makes use of careful locking and transaction sequences to guarantee consistency without using 2PC. This gives the best of both worlds, with t
This will be fixed by https://github.com/vitessio/website/pull/1361

2023-01-26 13:10 UTC, frouioui commented on content/en/docs/15.0/reference/features/vindexes.md
> +Consistent lookup vindexes use an alternate approach that makes use of careful locking and transaction sequences to guarantee consistency without using 2PC. This gives the best of both worlds, with t
I agree with what @mattlord said. We shall link to https://github.com/vitessio/vitess/issues/4855 directly.

2023-01-26 13:12 UTC, frouioui reviewed
Please update `content/en/docs/15.0/reference/features/vindexes.md` in this PR

2023-01-26 16:16 UTC, dogukanteber commented
I made the necessary changes. Just to let you guys know

2023-01-26 16:20 UTC, mattlord approved these changes
Thanks again, @dogukanteber ! ❤️

2023-01-26 16:47 UTC, mattlord commented
@dogukanteber would you mind doing an empty commit+push? The GitHub action is off in the weeds and I can't do anything in these cases (happens sometimes) other than push, but I can't push to your fork. 🙂 Sorry.

2023-01-26 16:50 UTC, merged