fixed v16 internal links
vitessio/website pull request #1360
Opened 2023-01-25 17:10 UTC by PaarthAgarwal

Fixed v16 internal links and target hashes. Fixes #1170.

2023-01-25 23:21 UTC, nate-double-u commented
Thanks for this @PaarthAgarwal, please sign the DCO -- this repository requires each commit to be signed before we merge. You can find the instructions here: https://github.com/vitessio/website/pull/1360/checks?check_run_id=10883304143

2023-01-25 23:49 UTC, nate-double-u commented
I've approved the preview, so you can see the preview here: https://deploy-preview-1360--vitess.netlify.app/

2023-01-26 11:14 UTC, PaarthAgarwal commented
Finally signed off. Had to regenerate my personal access token but worth it haha

2023-01-26 13:12 UTC, frouioui requested changes, later dismissed

2023-01-26 13:12 UTC, frouioui commented on content/en/docs/16.0/reference/features/vindexes.md
> +Consistent lookup vindexes use an alternate approach that makes use of careful locking and transaction sequences to guarantee consistency without using 2PC. This gives the best of both worlds, with t
The link to consistent lookup vindex design documentation should be: https://github.com/vitessio/vitess/issues/4855.

2023-01-26 20:45 UTC, nate-double-u commented
> Finally signed off. Had to regenerate my personal access token but worth it haha

Thanks for doing that! Should be easier now for your next PRs 🙂

2023-01-27 10:36 UTC, PaarthAgarwal commented on content/en/docs/16.0/reference/features/vindexes.md
> +Consistent lookup vindexes use an alternate approach that makes use of careful locking and transaction sequences to guarantee consistency without using 2PC. This gives the best of both worlds, with t
Done!

2023-01-27 16:44 UTC, mattlord approved these changes
Thanks again, @PaarthAgarwal ! ❤️

2023-01-28 17:44 UTC, merged