fixing broken link
vitessio/website pull request #1467
Opened 2023-05-10 21:42 UTC by hallaroo

Fixing one link that 404's

2023-05-22 14:00 UTC, ajm188 requested changes, later dismissed
right change, just need to make it in a different spot (and fix it everywhere!)

2023-05-22 14:00 UTC, ajm188 commented on content/en/docs/16.0/reference/programs/vtctldclient/vtctldclient_TabletExternallyReparented.md
> +See the Reparenting guide for more information: https://vitess.io/docs/user-guides/configuration-advanced/reparenting/#external-reparenting.
This is autogenerated from the code (https://github.com/vitessio/vitess/blob/main/go/cmd/vtctldclient/command/reparents.go#L291-L293)

Can you fix it there, then run (in this repo) `make vtctldclient-docs`?

2023-06-18 19:04 UTC, deepthi commented
@ajm188 can you take care of this?

2023-06-20 10:24 UTC, ajm188 commented
https://github.com/vitessio/vitess/pull/13350

2023-06-20 15:17 UTC, hallaroo commented
Thank you! And apologies for not responding sooner! This was on my get to this eventually list so thank you again for dealing with it.

2023-06-26 19:53 UTC, ajm188 commented
oh no i rebased when i meant to merge 🙈

2023-06-30 14:45 UTC, deepthi approved these changes

2023-06-30 14:45 UTC, merged