Capitalization Update in Header
vitessio/website pull request #1824
Opened 2024-08-20 10:55 UTC by mhmohona

I have noticed in most headline PascalCase is used. However, in some cases PascalCase was not used. This PR implements a PascalCase capitalization update across various header in the documentation to enhance readability and consistency in documentation headers.

2024-08-20 18:31 UTC, mattlord commented
LGTM, thanks @mhmohona ! Can you resolve the conflict? I can then approve and merge.

2024-08-21 00:47 UTC, mhmohona commented
@mattlord I have done so. Could you please have a look?

2024-08-21 13:29 UTC, mattlord requested changes

2024-08-21 13:29 UTC, mattlord commented on content/en/docs/21.0/reference/features/vitess-sequences.md
>  ```
We seem to be deleting content in this file.

2024-08-21 13:29 UTC, mattlord commented on content/en/docs/21.0/reference/programs/vtctldclient/_index.md
The vtctldclient reference docs are built from source so all of these changes will be lost. The changes would need to be made in the source and then the reference docs rebuilt (see the Makefile).

The tools used are the internal docgen tool: https://github.com/vitessio/vitess/blob/main/go/cmd/internal/docgen/docgen.go Which leverages cobra's doc tool: https://pkg.go.dev/github.com/spf13/cobra@v1.8.1/doc

2024-08-21 13:29 UTC, mattlord commented on content/en/docs/21.0/reference/programs/vtctldclient/_index.md
This makes me think that perhaps we should go in the other direction and standardize around this casing (only capitalizing the first word and of course any proper nouns).

2024-08-22 02:44 UTC, mhmohona commented on content/en/docs/21.0/reference/features/vitess-sequences.md
>  ```
Hey @mattlord, thank you so much for going through all the changes I made. 
Here the code block is intact. As you can see in preview - https://deploy-preview-1824--vitess.netlify.app/docs/21.0/reference/features/vitess-sequences/#creating-a-sequence

and in actual file - https://github.com/mhmohona/vitessio-website/blob/headline-fix/content/en/docs/21.0/reference/features/vitess-sequences.md?plain=1#L125

2024-08-24 15:18 UTC, mhmohona commented on content/en/docs/21.0/reference/programs/vtctldclient/_index.md
Yea, after changing some files, only then I noticed that these files are auto generated. 😅 Thanks for giving me details. I will check it.

2024-09-11 00:17 UTC, deepthi commented
I disagree with most of the changes to hand-written docs. There is no need to capitalize everything in those headings. As @mattlord pointed out the vtctld command reference docs are auto-generated, and any changes to those need to happen in the tool. I think we should close this PR, and decide whether it is worth changing docgen. If we want to change it, that would be a PR on vitessio/vitess.

2024-09-11 21:46 UTC, deepthi commented
@mhmohona We appreciate that you are spending time on this. In future, it will be better to propose changes in an issue and get some feedback before you start making changes. That will ensure that both your time and maintainer time is used wisely, and not wasted on PRs that ultimately don't get merged.

2024-09-12 05:06 UTC, closed without merging