Fix documentation around using xtrabackup as backup engine
vitessio/website pull request #310
Opened 2019-10-18 20:04 UTC by hwang381

Fix documentation around using xtrabackup as backup engine

Resolves #261

2019-10-21 22:12 UTC, deepthi requested changes
Thank you for creating this PR. We definitely appreciate the help.

2019-10-21 22:12 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> +vtctl Backup <tablet-alias> -backup_engine_implementation=builtin
There is no such option to the `Backup` command.

2019-10-21 22:12 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> -* Xtrabackup
+1

2019-10-21 22:12 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> -    <tr>
This block should be added back.

2019-10-21 22:12 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> +Current, we have plugins for:
Current -> Currently

2019-10-21 22:12 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> +If `backup_engine_implementation` is `builtin`, in response to this command, the designated tablet performs the following
Revert this change.

2019-10-21 22:12 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> +If `backup_engine_implementation` is `xtrabackup`, we do not do any of the above. The tablet can
Revert this change.

2019-10-24 06:19 UTC, hwang381 commented
All comments have been addressed @deepthi

2019-10-25 03:44 UTC, deepthi commented
@hwang381 you have to fix the DCO check. You can do that by rebasing and fixing each commit comment to have a signoff line, and then force-push.

2019-10-25 03:46 UTC, deepthi commented on content/en/docs/user-guides/backup-and-restore.md
> +    </tr>
There are 3 other flags:
xtrabackup_root_path
xtrabackup_stripes
xtrabackup_stripe_block_size.

Would you be able to add these to the docs?

2019-10-29 03:03 UTC, deepthi approved these changes
LGTM

2019-10-29 03:04 UTC, merged