First draft of 7.0 release notes
vitessio/website pull request #472
Opened 2020-07-19 14:17 UTC by deepthi

Signed-off-by: deepthi <deepthi@planetscale.com>

2020-07-22 07:46 UTC, rohit-nayak-ps requested changes
Rest LGTM

2020-07-22 07:46 UTC, rohit-nayak-ps commented on content/en/blog/2020-07-28-announcing-vitess-7.md
> +Vitess 7 adds ease-of-use and many new features built on top of VReplication. VStream Copy allows streaming of entire tables or databases.
Should we add more end-user perspective: 
VStream Copy allows streaming of entire tables or databases enabling change data capture for applications like data warehousing. 
Schema Versioning tracks ddls to record schema changes and associated gtid positions. Replication streams running past events will now see the correct schema. In addition it enables tracking and auditing schema changes.

2020-07-22 20:02 UTC, deepthi commented on content/en/blog/2020-07-28-announcing-vitess-7.md
> +Vitess 7 adds ease-of-use and many new features built on top of VReplication. VStream Copy allows streaming of entire tables or databases.
I'll add a few more words, but we are trying to keep this short to encourage people to read the release notes. Those should be more descriptive.

2020-07-22 20:32 UTC, rohit-nayak-ps approved these changes

2020-07-27 16:51 UTC, harshit-gangal approved these changes

2020-07-27 21:09 UTC, sougou approved these changes

2020-07-28 14:32 UTC, merged