updated location of recovery document
vitessio/website pull request #486
Opened 2020-08-03 17:55 UTC by arindamnayak

2020-08-03 19:35 UTC, deepthi commented
One more request. Can we list MySQL & ripple under pre-conditions?
Or right at the top we can put a "Supported databases" and list them there. It should be very clear to people that MariaDB is not supported, nor have we tested with any binlog server other than ripple.

2020-08-04 06:39 UTC, arindamnayak commented
> One more request. Can we list MySQL & ripple under pre-conditions?
> Or right at the top we can put a "Supported databases" and list them there. It should be very clear to people that MariaDB is not supported, nor have we tested with any binlog server other than ripple.

@deepthi , updated the document, please have a look. I havn't put the mysql and ripple together, Mentioned mysql at top and put ripple as pre-condition saying `currently it is tested with ripple` .

2020-08-04 17:05 UTC, deepthi requested changes

2020-08-04 17:05 UTC, deepthi commented on content/en/docs/reference/features/recovery.md
> +### Support Databases
```suggestion
### Supported Databases
```

2020-08-04 17:56 UTC, arindamnayak commented on content/en/docs/reference/features/recovery.md
> +### Support Databases
done

2020-08-04 18:01 UTC, deepthi approved these changes

2020-08-04 18:01 UTC, merged