Add Materialize user guide.
vitessio/website pull request #497
Opened 2020-08-26 05:06 UTC by aquarapid

Signed-off-by: Jacques Grove <aquarapid@gmail.com>

2020-08-28 10:07 UTC, rohit-nayak-ps requested changes
This is brilliant.

I flagged a couple of typos and suggested use of VExec/Workflow if you feel it is appropriate.

2020-08-28 10:07 UTC, rohit-nayak-ps commented on content/en/docs/user-guides/materialize.md
> +Since `Materialize` uses VReplication, the view can be kept up-to-date very close to real-time, which enables use-cases like creating copies of the same table sharded different ways for the purposes
"certain sets queries" : did you mean "certain sorts (or types) of queries:?

2020-08-28 10:07 UTC, rohit-nayak-ps commented on content/en/docs/user-guides/materialize.md
> +In the case where we using `Materialize` to copy tables between keyspaces, we can use the `"create_ddl": "copy"` option in the `Materialize` `json_spec` `table_settings` to create the target table fo
Typo: Materilize --> Materialize

2020-08-28 10:07 UTC, rohit-nayak-ps commented on content/en/docs/user-guides/materialize.md
> +Again, we can add a column to the source table, and see it replicated into the target table:
"add a column" --> "add a row"

2020-08-28 10:07 UTC, rohit-nayak-ps commented on content/en/docs/user-guides/materialize.md
> +You can also use the `VReplicationExec` command to temporarily stop the replication streams for the VReplication streams that make up the `Materialize` process.  For example, to stop both streams, yo
Do we want to show the VExec and Workflow commands here?

- vtctlclient VExec commerce.copy_corder_1 "select * from _vt.vreplication"
- vtctlclient Workflow commerce.copy_corder_1 show
- vtctlclient Workflow commerce.copy_corder_1 stop
- vtctlclient Workflow commerce.copy_corder_1 start
- vtctlclient Workflow commerce.copy_corder_1 delete

2020-09-01 01:57 UTC, aquarapid commented on content/en/docs/user-guides/materialize.md
> +You can also use the `VReplicationExec` command to temporarily stop the replication streams for the VReplication streams that make up the `Materialize` process.  For example, to stop both streams, yo
Let's merge without it;  I'll do a separate PR for that output when I have some time.

2020-09-01 14:10 UTC, rohit-nayak-ps approved these changes

2020-09-01 20:25 UTC, merged