Tablet throttler documentation (references/features)
vitessio/website pull request #512
Opened 2020-09-09 13:09 UTC by shlomi-noach

Documenting https://github.com/vitessio/vitess/pull/6668: the tablet throttler. background, overview, configuration, API, usage

Only merge once https://github.com/vitessio/vitess/pull/6668 is merged.

2020-09-24 08:17 UTC, shlomi-noach commented
ping. Request for review :pray:

2020-10-06 16:21 UTC, aquarapid approved these changes
Pushed some slight changes.  LGTM

2020-10-06 17:06 UTC, deepthi commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
typo: entires -> entries

2020-10-06 17:06 UTC, deepthi commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler is intended for use only by application such as the above mass write cases. It should not be used for ongoing, normal OLTP queries.
```suggestion
The throttler is intended for use only for operations such as the above mass write cases. It should not be used for ongoing, normal OLTP queries.
```

2020-10-06 17:06 UTC, deepthi commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler chooses the response by comparing the replication lag with a pre-defined _threshold_. If the lag is lower than the threshold, response can be `200` (OK). I the lag is higher than the th
```suggestion
The throttler chooses the response by comparing the replication lag with a pre-defined _threshold_. If the lag is lower than the threshold, response can be `200` (OK). If the lag is higher than the threshold, response would be `429` (Too Many Requests).
```

2020-10-06 17:06 UTC, deepthi commented on content/en/docs/reference/features/tablet-throttler.md
> +- `"IsDormant": false,` means an app has recently issues a `check`, and the throttler is probing for lag at high frequency.
```suggestion
- `"IsDormant": false,` means an app has recently issued a `check`, and the throttler is probing for lag at high frequency.
```

2020-10-06 17:06 UTC, deepthi commented on content/en/docs/reference/features/tablet-throttler.md
> +- Apps may further declare themselves to be _low priority_ via `?p=low` param. Managed online schema migrations (`gh-ost`, `pt-online-schema-change`) do so, as does the table purge process.
what is the significance of `low` priority?

2020-10-07 06:14 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +- Apps may further declare themselves to be _low priority_ via `?p=low` param. Managed online schema migrations (`gh-ost`, `pt-online-schema-change`) do so, as does the table purge process.
It's actually very significant: today, we only use the throttler fo rstrictly offline processes: schema migrations and table purging. But, in the future, an app may want to use the throttler for bulk writes, imports, etc. The app is less tolerant to delays. If the app wants to import 10,000,000 rows into a table, and a migration runs on another table, then the two will collide; they will both make slow progress, but while th emigration doesn't case, the app will care. That's why we put migrations and table purges on `low` priority, such that they will yield to apps with "normal" priority. At GitHub, this change made a huge impact to application behavior.

2020-10-07 06:17 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +- `"IsDormant": false,` means an app has recently issues a `check`, and the throttler is probing for lag at high frequency.
fixed

2020-10-07 06:17 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler chooses the response by comparing the replication lag with a pre-defined _threshold_. If the lag is lower than the threshold, response can be `200` (OK). I the lag is higher than the th
fixed

2020-10-07 06:17 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler is intended for use only by application such as the above mass write cases. It should not be used for ongoing, normal OLTP queries.
fixed

2020-10-07 06:17 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
fixed

2020-10-07 18:29 UTC, bnlandry requested changes
This document contains very thorough information. Most of my comments are stylistic.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +title: Tablet throttler
I think that at a high level, this doc should be two docs: one is the concept doc, which includes the first section ("Why Throttler"), and then a reference doc that includes the rest. Someone looking for configuration information will otherwise have to search through the concept information.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +VTTablet runs a cooperative throttling service, that probes the shard's MySQL topology and observes replication lag on servers. This throttler is derived from GitHub's [freno](https://github.com/gith
```suggestion
VTTablet runs a cooperative throttling service. This service probes the shard's MySQL topology and observes replication lag on servers. This throttler is derived from GitHub's [freno](https://github.com/github/freno).
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +VTTablet runs a cooperative throttling service, that probes the shard's MySQL topology and observes replication lag on servers. This throttler is derived from GitHub's [freno](https://github.com/gith
This says that the throttler observes replication lag, but it appears it does other things as well. Let's include a brief summary of those other features in this overview paragraph. E.g., provides throttling advice to applications?

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +## Why throttler
I think it's most useful when section titles summarize the thesis of the section. Here, it might be, "Throttler monitors replica lag."

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
```suggestion
Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary instance that applies changes and logs them to the binary log. The replicas for that shard will get binary log entries from the primary, acknowledge them if semi-synchronous replication is enabled, and apply them. A running replica normally applies the entire set as soon as possible, unless it is stopped or configured to delay. However, if the replica is busy, then it may not have the resources to apply events in a timely fashion, and can therefore start lagging.  For example, if the replica is serving traffic, it may lack the necessary disk I/O or CPU to avoid lagging behind the primary.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
I made a couple of inferences about the right word choice in this suggestion; please review before applying.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Maintaining low replication lag is important in production:
```suggestion
Maintaining low replication lag is important in production for two reasons:
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
I replaced the first use of 'primary' with 'primary instance,' which may be wrong. If this means the same as 'master', then 'master' is the usage that prevails in the existing docs currently. I believe Sougou made the call that we would not retrofit the code and docs with the emerging standard usage 'primary', but please correct if I'm mistaken.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- A lagging replica may not be representative of the data on the primary. Reads from the replica reflect data that is not consistent with the primary's. This is noticeable on web services following r
```suggestion
- A lagging replica may not be representative of the data on the primary. Reads from the replica reflect data that is not consistent with the data on the primary. This is noticeable on web services following read-after-write from the replica, and this can produce results not reflecting the write.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- An up-to-date replica makes for a good failover experience. If all replicas are lagging, then a failover process must choose between waiting for a replica to catch up, or losing data.
```suggestion
- An up-to-date replica makes for a good failover experience. If all replicas are lagging, then a failover process must choose between waiting for a replica to catch up or losing data.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Some common database operations include mass writes to the database:
```suggestion
Some common database operations include mass writes to the database, including the following:
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Online schema migrations, duplicating entire tables.
```suggestion
- Online schema migrations duplicating entire tables
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Mass population of columns (e.g. following a `ADD COLUMN` migration, populate the new column with derived value).
```suggestion
- Mass population of columns, such as populating the new column with derived values following an `ADD COLUMN` migration
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Purging of old data.
```suggestion
- Purging of old data
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Purging of tables as part of safe table `DROP` operation.
```suggestion
- Purging of tables as part of safe table `DROP` operation
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +This is where a throttler gets in. A throttler can tell "replication lag is low, cluster is healthy, go ahead and do some work" or it may say "replication lag is high, please hold your next operation
```suggestion
This is where a throttler becomes useful. A throttler can detect when replication lag is low, a cluster is healthy, and operations can proceed. It can also detect when replication lag is high and advise applications to hold the next operation.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +This is where a throttler gets in. A throttler can tell "replication lag is low, cluster is healthy, go ahead and do some work" or it may say "replication lag is high, please hold your next operation
Some more inferences here; please review before applying.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Applications are expected to break down their tasks into small sub-tasks (e.g. instead of deleting `1,000,000` rows, only delete `50` at a time), and check in with the throttler in-between.
```suggestion
Applications are expected to break down their tasks into small sub-tasks. For example, instead of deleting `1,000,000` rows, an application should only delete `50` at a time. Between these sub-tasks, the application should check in with the throttler.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler is intended for use only for operations such as the above mass write cases. It should not be used for ongoing, normal OLTP queries.
```suggestion
The throttler is only intended for use with operations such as the above mass write cases. It should not be used for ongoing, normal OLTP queries.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Each `vttablet` runs an internal throttler service, and provides API endpoints to the throttler. Only the primary throttler is doing actual work at any given time. The throttlers on the replicas are
```suggestion
Each `vttablet` runs an internal throttler service, and provides API endpoints to the throttler. Only the primary throttler is doing actual work at any given time. The throttlers on the replicas are mostly dormant, and wait for their turn to become "leaders," such as when the tablet transitions into `MASTER` (primary) type.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The primary tablet's throttler does the following things, continuously:
```suggestion
The primary tablet's throttler continuously does the following things:
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Confirm it's still the primary tablet for its shard.
```suggestion
- The throttler confirms it is still the primary tablet for its shard.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Every `10sec`, use topology server to refresh the shard's tablets list
```suggestion
- Every `10sec`, the throttler uses the topology server to refresh the shard's tablets list.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Probe all `REPLICA` tablets for their replication lag. This is done by querying the `_vt.heartbeat` table.
```suggestion
- The throttler probes all `REPLICA` tablets for their replication lag. This is done by querying the `_vt.heartbeat` table.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +  - Throttler begins in dormant probe mode. As long as no app/client is actually looking for metrics, it probes the servers in multi-second interval.
```suggestion
  - The throttler begins in dormant probe mode. As long as no application or client is actually looking for metrics, it probes the servers at multi-second intervals.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +  - When apps check for throttle advice, it begins probing servers in subsecond intervals. It reverts to dormant probe mode if no requests are made in the duration of `1min`.
```suggestion
  - When applications check for throttle advice, the throttler begins probing servers in subsecond intervals. It reverts to dormant probe mode if no requests are made in the duration of `1min`.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Aggregate last probed value from all relevant tablets; this is _the cluster's metric _.
```suggestion
- The throttler aggregates the last probed values from all relevant tablets. This is _the cluster's metric _.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The cluster's metric is only as accurate as:
```suggestion
The cluster's metric is only as accurate as the following metrics:
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- The probe interval,
```suggestion
- The probe interval
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- The heartbeat injection interval, and
```suggestion
- The heartbeat injection interval
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The error margin is about the sum of the above values, plus additional overhead. Default probe interval is `100ms`, aggregation interval is `100ms` and default heartbeat interval is `250ms`. The latt
```suggestion
The error margin equals approximately the sum of the above values, plus additional overhead. The defaults for these intervals are as follows:
+ Probe interval: `100ms`
+ Aggregation interval: `100ms`
+ Heartbeat interval: `250ms`

The user may override the heartbeat interval by sending `-heartbeat_interval` flag to `vttablet`.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Thus, the aggregated interval can be off, by default, by some `500ms`. This makes it inaccurate for evaluations that require high resolution lag evaluation. Fortunately, for throttling purposes, this
```suggestion
Thus, the aggregated interval can be off, by default, by some `500ms`. This makes it inaccurate for evaluations that require high resolution lag evaluation. This resolution is sufficient for throttling purposes.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler allows clients/apps to `check` for throttle advice. The check is a `HTTP` request, `HEAD` or `GET` method. Throttler returns a HTTP response code as an answer:
```suggestion
The throttler allows clients and applications to `check` for throttle advice. The check is an `HTTP` request, `HEAD` method, or `GET` method. Throttler returns one of the following HTTP response codes as an answer:
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `200` (OK): Application may write to data store. This is the desired response.
```suggestion
- `200` (OK): The application may write to the data store. This is the desired response.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `404` (Not Found): Unknown metric name. This can take place immediately upon startup or immediately after failover, and should resovle within 10 seconds.
```suggestion
- `404` (Not Found): The check contains an unknown metric name. This can take place immediately upon startup or immediately after failover, and should resolve within 10 seconds.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `417` (Expectation Failed): Requesting application is explicitly forbidden to write. Tablet throttler does not implement this at this time.
```suggestion
- `417` (Expectation Failed): The requesting application is explicitly forbidden to write. The throttler does not implement this at this time.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `429` (Too Many Requests): Do not write. A normal, expected state indicating there is replication lag. This is the hint for apps/clients to withhold writes.
```suggestion
- `429` (Too Many Requests): Do not write. A normal, expected state indicating there is replication lag. This is the hint for applications or clients to withhold writes.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `500` (Internal Server Error): Internal error. Do not write.
```suggestion
- `500` (Internal Server Error): An internal error has occurred. Do not write.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler chooses the response by comparing the replication lag with a pre-defined _threshold_. If the lag is lower than the threshold, response can be `200` (OK). If the lag is higher than the t
```suggestion
The throttler chooses the response by comparing the replication lag with a pre-defined _threshold_. If the lag is lower than the threshold, response can be `200` (OK). If the lag is higher than the threshold, the response would be `429` (Too Many Requests).
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +The throttler only collects and evaluates lag on a set of predefined tablet types. By default, this tablet type set is `REPLICA`. See configuration, below.
```suggestion
The throttler only collects and evaluates lag on a set of predefined tablet types. By default, this tablet type set is `REPLICA`. See [Configuration](#Configuration).
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +When the throttler sees no relevant replicas in the shard, the behavior is to allow writes (respond with `HTTP 200 OK`).
```suggestion
When the throttler sees no relevant replicas in the shard, it allows writes by responding with `HTTP 200 OK`.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Use the `vttablet` flag `-throttle_threshold` to set a lag threshold value, e.g. `-throttle_threshold=0.5s` for a half second. The default threshold is `1sec` and is set upon tablet startup.
```suggestion
- Use the `vttablet` flag `-throttle_threshold` to set a lag threshold value. The default threshold is `1sec` and is set upon tablet startup. For example, to set a half-second lag threshold, use the flag `-throttle_threshold=0.5s`.



```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Use the `vttablet` flag `-throttle_tablet_types="replica,rdonly"` to set the tablet types which are queried for lag and considered by the throttler. `replica` is always implicitly included (and the
```suggestion
- To set the tablet types that the throttler queries for lag, use the `vttablet` flag `-throttle_tablet_types="replica,rdonly"`. The default tablet type is `replica`; this type is always implicitly included in the tablet types list. You may add any other tablet type. Any type not specified is ignored by the throttler.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Apps will use `/throttler/check`
```suggestion
Applicaitons use the API `/throttler/check`.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Apps may indicate their identity via `?app=<name>` param.
```suggestion
- Applications may indicate their identity via `?app=<name>` parameter.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- Apps may further declare themselves to be _low priority_ via `?p=low` param. Managed online schema migrations (`gh-ost`, `pt-online-schema-change`) do so, as does the table purge process.
```suggestion
- Applications may also declare themselves to be _low priority_ via `?p=low` param. Managed online schema migrations (`gh-ost`, `pt-online-schema-change`) do so, as does the table purge process.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- A data backfill app may use: `/throttler/check?app=backfill` (using _normal_ priority)
```suggestion
- A data backfill application may use this parameter: `/throttler/check?app=backfill` (using _normal_ priority)
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +A `HEAD` request is sufficient. A `GET` request also provides a `JSON` output. Examples:
```suggestion
A `HEAD` request is sufficient. A `GET` request also provides a `JSON` output. For example:
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +In the above we can see that the tablet is configured to throttle at `1sec`
```suggestion
In the above examples we can see that the tablet is configured to throttle at `1sec`
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +In the above we can see that the tablet is configured to throttle at `1sec`
Is this true in the third example?

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Tablet also provides `/throttler/status` endpoint. This is useful for monitoring/management purposes. Examples:
```suggestion
Tablet also provides `/throttler/status` endpoint. This is useful for monitoring and management purposes. 
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +On a `primary`, healthy tablet:
```suggestion
**Example: Healthy primary tablet**
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +
```suggestion
The following command requests throttler advice including JSON output on a tablet named `tablet1` on port 15100.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +
I'm not sure I am interpreting the API call accurately here. Please review before commiting.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +```json
```suggestion

This API call returns the following JSON object:

```json
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Notable:
```suggestion
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `"IsLeader": true` indicates this tablet is active, is the `primary`, and is running probes
```suggestion
`"IsLeader": true` indicates this tablet is active, is the `primary`, and is running probes.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +- `"IsDormant": false,` means an app has recently issued a `check`, and the throttler is probing for lag at high frequency.
```suggestion
`"IsDormant": false,` means that an application has recently issued a `check`, and the throttler is probing for lag at high frequency.
```

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +On a `REPLICA` tablet:
**Example: Replica Tablet**

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +
The following command requests throttler advice including JSON output on a tablet named `tablet2` on port 15100.

2020-10-07 18:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +```json
```suggestion

This API call returns the following JSON object:

```json
```

2020-10-08 04:56 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
Yeah, good point about master/primary. I'll take it to the team.

2020-10-08 05:01 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +This is where a throttler gets in. A throttler can tell "replication lag is low, cluster is healthy, go ahead and do some work" or it may say "replication lag is high, please hold your next operation
Good rewrite, thank you!

2020-10-08 05:36 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +In the above we can see that the tablet is configured to throttle at `1sec`
Fixed and clarified this is only true in first two examples.

2020-10-08 05:39 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +
fixed and clarified.

2020-10-08 05:44 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +
fixed

2020-10-08 05:44 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +On a `REPLICA` tablet:
fixed

2020-10-08 05:45 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +## Why throttler
fixed

2020-10-08 08:24 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +title: Tablet throttler
That's a good point. I think it's a more general question on how we approach our docs. Do we split by:

- context, problem space
- common practices
- configuration & usage
- examples

or do we aggregate them all in the same doc (as done here). I'd like to take that discussion further, and outside this PR. cc @askdba @deepthi @sougou

2020-10-11 09:46 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess uses MySQL with asynchronous or semi-synchronous replication. In these modes, each shard has a primary that applies changes and logs them to the binary log. The replicas for that shard will ge
We have agreed to use the term "primary" over "master" in this document. I have added a clarification in the first paragraph about the change of terminology.

2020-10-13 05:32 UTC, shlomi-noach commented
ping

@bnlandry I've responded to all but one review comments (see following) - does this look good now?

@askdba @deepthi @sougou please see my question: https://github.com/vitessio/website/pull/512#discussion_r501536551

2020-10-13 16:53 UTC, deepthi commented on content/en/docs/reference/features/tablet-throttler.md
> +title: Tablet throttler
I agree that we take this discussion outside this PR and not hold it up.

2020-10-14 19:29 UTC, bnlandry approved these changes
LGTM!

2020-10-14 19:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +_Note: the Vitess documentation is transitioning from the term "Master" (with regard to MySQL replication) to "Primary". this document reflects this transition._
```suggestion
_Note: with regard to MySQL replication, the Vitess documentation is transitioning from the term 'master' to the term 'primary.' This document reflects this transition._
```

2020-10-14 19:29 UTC, bnlandry commented on content/en/docs/reference/features/tablet-throttler.md
> +Thus, the aggregated interval can be off, by default, by some `500ms`. This makes it inaccurate for evaluations that require high resolution lag evaluation. This resolution is sufficient for throttli
```suggestion
Thus, the aggregated interval can be off, by default, by about `500ms`. This makes it inaccurate for evaluations that require high resolution lag evaluation. This resolution is sufficient for throttling purposes.
```

2020-10-15 05:47 UTC, merged