Adding in new VTExplain in bulk user guide
vitessio/website pull request #530
Opened 2020-09-24 19:09 UTC by hallaroo

Adding in new user guide and making small edits

2020-09-28 20:44 UTC, bnlandry requested changes, later dismissed
Nice work! Edits are mostly for style, and could use SME review.

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +title: Explaining how to analyze SQL statements in bulk
```suggestion
title: Analyzing SQL statements in bulk
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +This document covers the way our [VTexplain tool](../../reference/vtexplain) can be used to evaluate how Vitess executes many SQL statements.
```suggestion
This document covers the way our [VTexplain tool](../../reference/vtexplain) can be used to evaluate how Vitess executes multiple SQL statements. 
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +To successfully analyze many SQL queries and determine how Vitess executes each statement, follow these steps:
```suggestion
To analyze multiple SQL queries and determine how Vitess executes each statement, follow these steps:
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +These queries should be most, if not all, of the queries that are sent to your current production database tracked over an extended period of time. You may need to track your sent queries for days or
```suggestion
These queries should be most, if not all, of the queries that are sent to your current production database tracked over an extended period of time. You may need to track your sent queries for days or weeks depending on your setup. You will need to normalize the queries you will be analyzing. To do this, you can use any MySAL monitoring tool, like VividCortex, Monyog, or PMM.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +Queries that are not supported or are coming from other sources should be removed from your normalized list. A few examples of queries to remove are:
```suggestion
Remove from your list any unsupported queries or queries from non-application sources. The following are examples of queries to remove:
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +* LOCK/UNLOCK TABLES  -  These are likely coming from schema management tools, which you wouldn't want run against vtgate
```suggestion
* LOCK/UNLOCK TABLES  -  These likely come from schema management tools, which VTGate obviates.

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +* FLUSH/PURGE LOGS  - These are likely coming from management scripts
```suggestion
* FLUSH/PURGE LOGS  - Vitess performs its own log management.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +* performance_schema queries  -  This is not supported by Vitess
```suggestion
* performance_schema queries  -  These queries are not supported by Vitess.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +* BEGIN/COMMIT  -  These are supported, but not as stand-alone queries in vtexplain
```suggestion
* BEGIN/COMMIT  -  Vitess supports these statements, but VTExplain does not.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +An example pipeline to filter out these specific queries is:
```suggestion
The following is an example pipeline to filter out these specific queries:
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +Once the queries are normalized in prepared statement style you will need to generate a populate fake values in order for VTExplain to run properly. An example pipeline you can run to do this is:
```suggestion
Once the queries are normalized in prepared statement style, populate fake values to allow VTExplain to run properly. The following is an example pipeline you can run to populate fake values:
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +In order to analyze every query in your list you likely will want to run a script to do this. We have an example python script below that assumes a sharded setup with 4 shards that you will need to a
```suggestion
In order to analyze every query in your list, create and run a script. The following is an example Python script that assumes a sharded database with 4 shards. You can adjust this script to match your individual requirements.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +You will need to add your proposed SQL schema to the file created by the script (e.g. schema.sql). A very simple example SQL schema is below. You will need to create one that matches your needs.
```suggestion
Add your proposed SQL schema to the file created by the script (e.g. schema.sql). The following is an example SQL schema:
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +## 6. Add your VSchema
```suggestion
## 6. Add your VSchema to the output file
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +You will need to add your VSchema to the file created by the script (e.g. schema.json). A very simple example VSchema to match the SQL schema is below. You will need to create one that matches your n
```suggestion
Add your VSchema to the file created by the script: in this example, the file is named `schema.json`. The following is an example VSchema to match the example SQL schema above.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +Once you have your full output in vtexplain.output you can use grep for ERROR to review any issues found.
```suggestion
Once you have your full output in vtexplain.output, use `grep` to search for the string "ERROR" to review any issues that VTExplain found.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +The following query is scattered across both shards, and then aggregated by vtgate.
```suggestion
In the following example, VTGate scatters the example query across both shards, and then aggregates the query results.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +SELECT * from user
```suggestion
SELECT * FROM user
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +### Example: Error
```suggestion
### Example: Query returns an error
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +The following query produces an error because the AVG function isn't supported for scatter queries across multiple shards.
```suggestion
The following query produces an error because Vitess does not support the `AVG` function for scatter queries across multiple shards.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +2 -sql 'SELECT avg(balance) from user;'
```suggestion
2 -sql 'SELECT AVG(balance) FROM user;'
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +ERROR: vtexplain execute error in 'SELECT avg(balance) from user':
```suggestion
ERROR: vtexplain execute error in 'SELECT AVG(balance) FROM user':
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +### Example: Single shard
```suggestion
### Example: Targeting a single shard
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +```
```suggestion
```shell
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +SELECT * from user where user_id = 100
```suggestion
SELECT * FROM user WHERE user_id = 100
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +1 ks1/80-: select * from user where user_id = 100 limit 10001
```suggestion
1 ks1/80-: SELECT * FROM user WHERE user_id = 100 limit 10001
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain.md
>  In order to explain a statement, first identify the SQL schema for the tables that the statement will use. This includes tables that a query targets and tables that a DML statement modifies.
```suggestion
In order to explain a statement, first identify the SQL schema for the tables that the statement uses. This includes tables that a query targets and tables that a DML statement modifies.
```

2020-09-28 20:44 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain.md
> +If you have a large number of queries you would like to analyze for issues, based on a Vschema you’ve created for your database, you can read through a detailed scripted example [here](../../user-gui
```suggestion
If you have a large number of queries you want to analyze for issues, based on a Vschema for your database, you can read through a detailed scripted example [here](../../user-guides/vtexplain-in-bulk).
```

2020-09-30 19:21 UTC, bnlandry commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +1. Add your SQL schema
This step and the next one have vague titles. Consider being more specific. E.g., "Add your SQL schema to the output file."

2020-10-01 21:46 UTC, hallaroo commented on content/en/docs/user-guides/vtexplain-in-bulk.md
> +1. Add your SQL schema
I think I fixed it this time. For some reason I didn't see all of the changes you suggested the first time around. I made sure I got all of them this time.

2020-10-05 20:57 UTC, deepthi approved these changes
LGTM

2020-10-05 20:58 UTC, merged