Django Blog initial draft
vitessio/website pull request #597
Opened 2020-11-24 10:14 UTC by askdba

Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>

2020-11-24 12:51 UTC, askdba commented
@shlomi-noach I'm going to work on images next but this is how it looks so far. Can you do a quick review?

2020-11-24 14:32 UTC, shlomi-noach requested changes
Yo! I think this post needs the love of a native English speaker, I spotted multiple grammar issues, but I'm in no way authoritative on that. Otherwise, redice the amount of promotional wording at the beginning, see inline comments.

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +title: 'How to deploy Django Application with Vitess Kubernetes Operator?'
```suggestion
title: 'How to deploy Django Application with Vitess Kubernetes Operator'
```

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
> It’s also versatile, secure, and scalable just like Vitess

I'm not sure I understand the comparison to Vitess here, and not sure the readers will understand it. It sounds more like marketing pitch, where this blog post is technical. I suggest dropping this comparison.

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
>  including MySQL one of which Vitess is allowing a scalable database without ever having to change the application code.

Can't parse this sentence, grammatically. What did you mean to say here?

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
`s/opensource/open source`

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
> how to combine forces of two great free

again, let's tone down the promotional words

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Once the operator launched with an [example](https://github.com/askdba/vitess_frameworks/blob/main/django/operator/operator.yaml) backend database let’s just call it a “weatherapp”. We will create an
> Once the operator launched with an [example](https://github.com/askdba/vitess_frameworks/blob/main/django/operator/operator.yaml) backend database let’s just call it a “weatherapp”.

I think there's multiple grammar mistakes here. But I feel like you'd benefit from someone who is a native English speaker, or who is more professional in editing texts. Can you perhaps run this by Gretchen?

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Point your browser to http://127.0.0.1:8000/admin
```suggestion
Point your browser to [http://127.0.0.1:8000/admin](http://127.0.0.1:8000/admin)
```

2020-11-24 14:32 UTC, shlomi-noach commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Vitess is a very powerful sharding framework that comes with a built-in control plane that allows backend developers to adapt their applications easily. Combining powerful application frameworks such
Here, at the end, is actually a good place to put a superlative and otherwise self promotional text. So this part looks fine.

2020-11-24 16:04 UTC, askdba commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
It is mentioned in Django sites and verified by the developer advocate. I think it's a valid statement but I'm not a developer.

2020-11-24 16:06 UTC, askdba commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
I think it will read better if "including MySQL one of which Vitess is allowing a scalable database architecture without ever having to change the application code."

2020-11-30 00:58 UTC, deepthi commented
> Yo! I think this post needs the love of a native English speaker, I spotted multiple grammar issues, but I'm in no way authoritative on that. Otherwise, redice the amount of promotional wording at the beginning, see inline comments.

I have to agree with the comment about promotional wording. It sounds like it was written by a Django developer rather than a vitess maintainer.

2020-11-30 01:12 UTC, deepthi reviewed
Sorry for not reviewing this earlier. I have a bunch of suggestions.

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +title: 'How to deploy Django Application with Vitess Kubernetes Operator'
```suggestion
title: 'How to deploy a Django Application with the Vitess Kubernetes Operator'

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
```suggestion
Django is a popular framework for Python application developers. It includes packages which make tasks like authorization and content administration easier. Django supports a number of [databases](https://docs.djangoproject.com/en/3.1/ref/databases/) including MySQL which makes it possible to run a Django application over Vitess without having to change the application code. Let’s take a look at how to combine the strengths of these two open source frameworks. 

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Django is a popular framework for Python application developers to turn their ideas into products super fast. It is fully loaded with extra packages and makes many tasks easy such as authorization an
I have tried to rewrite the first paragraph by toning down some of the superlatives and making it more matter-of-fact.

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +First of all, we built the backend of this architecture pointing to the Vitess cluster. We’ll use the [Vitess operator](https://vitess.io/docs/get-started/operator/). You can see the details of the i
I don't understand what the first sentence is trying to convey. I would replace it with something like "We built this example using Vitess operator". WDYT?

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +For this example, we’re using GKE and the Kubernetes cluster already created. You can also do this via minikube locally.
```suggestion
For this example, we’re using GKE with an existing Kubernetes cluster. You can also do this via minikube locally. 

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Once the operator launches with an [example](https://github.com/askdba/vitess_frameworks/blob/main/django/operator/operator.yaml) backend database, let’s call it a “weatherapp”,we will create an init
Separate this into two sentences. First one should introduce weatherapp and what it is supposed to do. Next sentence can talk about creating the database.

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +(1) creating a Vitess Operator pod and (2) building Vitess Cluster Components (1x primary tablet, 1x replica tablet, 3x etcd pods, 1x vtgate,1x vtctld, 1x vitessbackup)
Use bullets or numbered list for these two steps.

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Initialize this cluster with a sample database called ‘weatherapp’ and user/password to access it will be embedded in the configuration [file](https://github.com/askdba/vitess_frameworks/blob/main/dj
```suggestion
Initialize this cluster with a sample database called ‘weatherapp’. The user/password to access it is embedded in the configuration [file](https://github.com/askdba/vitess_frameworks/blob/main/django/operator/101_initial_cluster.yaml.django). We are basically creating a database which is analogous to a keyspace in Vitess. 

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +As you can see Vitess is completely built over an unsharded keyspace with one “Primary (Master)” and one “Replica” and is a fully managed cluster.
```suggestion
As you can see this brings up a fully functional managed Vitess cluster with an unsharded keyspace consisting of one “Primary (Master)” and one “Replica”. 

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +At this point we go back to building the Django application now that we have set up the Vitess cluster with a MySQL backend. We  build a Django project using the django-admin command.
```suggestion
Now that we have set up the Vitess cluster with a MySQL backend, we can proceed to building the Django application. We will build a Django project using the django-admin command.

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Copy customs_db_backends directory to your project directory. You can clone [Vitess](https://github.com/vitessio/vitess/blob/d234083743d1cc9757ef673bf89be1a4a299b0b0/support/django/README.md) project
The link to clone vitess should be to the main repo instead of to the README file.

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +You may continue to build the application from this point on with an example [here](https://www.digitalocean.com/community/tutorials/how-to-build-a-weather-app-in-django).
```suggestion
You may continue to build the application from this point by following this [example](https://www.digitalocean.com/community/tutorials/how-to-build-a-weather-app-in-django). 

```

2020-11-30 01:12 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +At this stage, we’re ready to run the migration to initial Django metadata.
```suggestion
At this stage, we’re ready to run the migrations to create initial Django metadata. 

```

2020-11-30 09:10 UTC, askdba commented
> > Yo! I think this post needs the love of a native English speaker, I spotted multiple grammar issues, but I'm in no way authoritative on that. Otherwise, redice the amount of promotional wording at the beginning, see inline comments.
> 
> I have to agree with the comment about promotional wording. It sounds like it was written by a Django developer rather than a vitess maintainer.

We had Byron reviewed this blog and intentionally made it developer-friendly. After this review, Gretchen has taken an editorial review which I've incorporated already.

2020-11-30 09:17 UTC, askdba commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +First of all, we built the backend of this architecture pointing to the Vitess cluster. We’ll use the [Vitess operator](https://vitess.io/docs/get-started/operator/). You can see the details of the i
LGTM

2020-11-30 09:39 UTC, askdba commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Once the operator launches with an [example](https://github.com/askdba/vitess_frameworks/blob/main/django/operator/operator.yaml) backend database, let’s call it a “weatherapp”,we will create an init
I'm unable to break this, can you take another shot at it? :)

2020-11-30 17:14 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +Once the operator launches with an [example](https://github.com/askdba/vitess_frameworks/blob/main/django/operator/operator.yaml) backend database, let’s call it a “weatherapp”,we will create an init
How does this sound?
```
The Django example we are using is the ["weather app"] (link). We first launch the vitess operator using the provided [configuration] (link to operator.yaml). 
```
We don't need to mention database here because that only happens in the next step, when we deploy the 101_...yaml file.

2020-11-30 17:15 UTC, deepthi commented on content/en/blog/2020-11-30-how-to-deploy-django.md
> +First of all, we built this example using Vitess operator. We’ll use the [Vitess operator](https://vitess.io/docs/get-started/operator/). You can see the details of the implementation on the blog pos
"on the blog post" -> "in the blog post"
I think we can leave out "First of all".

2020-11-30 19:05 UTC, askdba commented
DCO failing , forking new branch .

2020-11-30 19:05 UTC, closed without merging