moving the faqs to FreshDesk
vitessio/website pull request #634
Opened 2020-12-10 18:18 UTC by hallaroo

2020-12-15 01:21 UTC, deepthi requested changes
The FAQ in freshdesk looks really cool!
However, I would like us to keep what we have under FAQ. We can still add a link to the freshdesk FAQ but make it explicit that it is provided by PlanetScale.
Something like "PlanetScale hosts an FAQ for Vitess"

2020-12-15 01:23 UTC, deepthi commented
cc @vitessio/maintainers

2020-12-15 17:18 UTC, hallaroo commented
> The FAQ in freshdesk looks really cool!

Yay! The organization features and the ability to easily/quickly add SEO to each Freshdesk support page are really nice as well.

> However, I would like us to keep what we have under FAQ. We can still add a link to the freshdesk FAQ but make it explicit that it is provided by PlanetScale.

Could we maybe have an FAQ similar to https://www.mysql.com/about/faq/ (eg pointers on where to find things) and have any longer or more specific content in FreshDesk? Otherwise we run the risk of having detailed content split between sites (which I'd like to avoid).

One of the questions can then have the specific call out referenced:

> Something like "PlanetScale hosts an FAQ for Vitess"

The other option of having an FAQ where all of the questions are written out as headers in list format on the website I think runs the risk of adding a lot of additional content that would be hard to keep organized on vitess.io. There are something like 98 published articles now and I have one more round of questions to add. 

What do you think?

2020-12-16 06:30 UTC, shlomi-noach commented
FreshDesk looks really nice! At some point we might consider using GitHub Discussions for Q&A

2020-12-16 20:34 UTC, deepthi requested changes

2020-12-16 20:34 UTC, deepthi commented on content/en/docs/faq/_index.md
> +
Can we add a line here about the videos we have on the vitess website itself and link to https://vitess.io/docs/resources/presentations/?

2020-12-16 20:35 UTC, deepthi commented on content/en/docs/faq/_index.md
> +## Where can I ask questions about Vitess?
This is really nice content :100:

2020-12-16 20:54 UTC, deepthi approved these changes

2020-12-16 20:55 UTC, merged