Documenting new Online DDL behavior for DROP TABLE
vitessio/website pull request #663
Opened 2021-01-07 10:59 UTC by shlomi-noach

Documenting changes in https://github.com/vitessio/vitess/pull/7221, which is already merged.

This PR documents the new `DROP TABLE` behavior when `ddl_strategy` is an online strategy.

2021-01-07 14:18 UTC, rohit-nayak-ps requested changes
lgtm
some nits

2021-01-07 14:18 UTC, rohit-nayak-ps commented on content/en/docs/reference/features/table-lifecycle.md
> +Vitess does not track the state of table lifecycle. The process is stateless thanks to an encoding schema in the table names. Examples:
Suggestion: Vitess does not track the state of table lifecycle => Vitess does not track the state of the table lifecycle
Typo:  an encoding schema =>  an encoding scheme

2021-01-07 14:18 UTC, rohit-nayak-ps commented on content/en/docs/user-guides/schema-changes/managed-online-schema-changes.md
> +  - Table is renamed into special name, identified by the [Table Lifecycle](../../../reference/features/table-lifecycle/) mechanism
Suggestion: Table is renamed into special name, identified by the => Table is renamed using a special naming convention, identified by the

2021-01-07 14:18 UTC, rohit-nayak-ps commented on content/en/docs/reference/features/table-lifecycle.md
> +Vitess does not track the state of table lifecycle. The process is stateless thanks to an encoding schema in the table names. Examples:
Suggestion: Vitess does not track the state of table lifecycle. => Vitess does not track the state of a table lifecycle.

2021-01-07 14:18 UTC, rohit-nayak-ps commented on content/en/docs/user-guides/schema-changes/managed-online-schema-changes.md
> +Use the standard MySQL `DROP TABLE` syntax. The query goes through the same [migration flow](#migration-flow-and-states) as `ALTER TABLE` does. Tables are not immediately dropped. Instead, they are r
Suggestion: then to slowly => to then slowly

2021-01-10 08:23 UTC, shlomi-noach commented on content/en/docs/user-guides/schema-changes/managed-online-schema-changes.md
> +Use the standard MySQL `DROP TABLE` syntax. The query goes through the same [migration flow](#migration-flow-and-states) as `ALTER TABLE` does. Tables are not immediately dropped. Instead, they are r
fixed

2021-01-10 08:23 UTC, shlomi-noach commented on content/en/docs/reference/features/table-lifecycle.md
> +Vitess does not track the state of table lifecycle. The process is stateless thanks to an encoding schema in the table names. Examples:
fixed

2021-01-10 08:23 UTC, shlomi-noach commented on content/en/docs/user-guides/schema-changes/managed-online-schema-changes.md
> +  - Table is renamed into special name, identified by the [Table Lifecycle](../../../reference/features/table-lifecycle/) mechanism
fixed

2021-01-10 08:24 UTC, shlomi-noach commented on content/en/docs/reference/features/table-lifecycle.md
> +Vitess does not track the state of table lifecycle. The process is stateless thanks to an encoding schema in the table names. Examples:
fixed

2021-01-10 14:53 UTC, rohit-nayak-ps approved these changes
lgtm

2021-01-10 14:53 UTC, merged