adding PDFs to git repo
vitessio/website pull request #692
Opened 2021-01-28 15:17 UTC by hallaroo

2021-01-28 20:14 UTC, deepthi requested changes
The paths to files need to be fixed.
Also, any reason we have the pdfs in the repo in two different folders? Can we have one copy?

2021-01-28 20:14 UTC, deepthi commented on content/en/docs/pdfs/_index.md
> +- [Vitess Docs 9.0 on January 26, 2021](https://github.com/vitessio/website/blob/mp-pdf-folder/static/files/version-pdfs/Vitess-Docs-9.0-01-26-2021.pdf)
This is referring to your branch. I believe you can link to relative paths for the files like how it is done here:
https://github.com/vitessio/website/blob/prod/content/en/docs/resources/presentations.md

2021-01-29 16:47 UTC, hallaroo commented on content/en/docs/pdfs/_index.md
> +- [Vitess Docs 9.0 on January 26, 2021](https://github.com/vitessio/website/blob/mp-pdf-folder/static/files/version-pdfs/Vitess-Docs-9.0-01-26-2021.pdf)
Yeah I only want one copy ... I thought I got them all from the same place but I must have copied and pasted incorrectly. I'll get that fixed ASAP.

2021-01-29 20:15 UTC, hallaroo commented on content/en/docs/pdfs/_index.md
> +- [Vitess Docs 9.0 on January 26, 2021](https://github.com/vitessio/website/blob/mp-pdf-folder/static/files/version-pdfs/Vitess-Docs-9.0-01-26-2021.pdf)
This should now match the example you linked.

2021-02-02 20:07 UTC, deepthi commented on content/en/docs/pdfs/_index.md
> +- [Vitess Docs 9.0 on January 26, 2021](https://github.com/vitessio/website/blob/mp-pdf-folder/static/files/version-pdfs/Vitess-Docs-9.0-01-26-2021.pdf)
Sorry if the example was misleading. We still want them to be just download links, we should not embed them using `ViewerJS`. Only the paths need to change (to be relative).

2021-02-02 20:08 UTC, deepthi commented
We still seem to have two copies of each file in this PR.
For example:
`static/files/version-pdfs/Vitess-Docs-5.0-02-04-2020.pdf` and `static/pdfs/Vitess Docs 5.0 (Feb 4 2020).pdf`

2021-02-05 16:57 UTC, deepthi approved these changes

2021-02-05 16:57 UTC, merged