Add basic query consolidation doc
vitessio/website pull request #703
Opened 2021-02-10 01:03 UTC by deepthi

2021-02-10 01:08 UTC, jmoldow commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +Then user2 issues an identical read while user1's read is still executing. In this case the consolidator will kick in and user2 will get the result of user1's query thereby losing read-after-write co
```suggestion
Then user2 issues an identical read while user1's read is still executing. In this case the consolidator will kick in and user2 will get the result of user1's query thereby losing read-after-write consistency.
```

2021-02-10 05:39 UTC, deepthi commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +Then user2 issues an identical read while user1's read is still executing. In this case the consolidator will kick in and user2 will get the result of user1's query thereby losing read-after-write co
Thank you :)

2021-02-10 15:43 UTC, hallaroo requested changes

2021-02-10 15:43 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +Query consolidation is a VTTablet feature.
Query consolidation is a VTTablet feature meant to protect your database from an overload caused by a spike in QPS for a specific query. 

Without this feature enabled such spikes can completely overwhelm the database. However, with this feature enabled the following will occur: when a vttablet receives a query, if an identical query is already in the process of being executed, the query will then wait.

**Note:** an identical query is one that is exactly the same, including literals and bind variables.

2021-02-10 15:43 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +* `-enable_consolidator`: Defaults to true.
Flags:

* `-enable_consolidator`: Defaults to true.
* `-enable_consolidator_replica`: Only enable query consolidation on non-primary tablets.

2021-02-10 15:43 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +* `-enable_consolidator`: Defaults to true.
This is just for formatting when I make the PDFs for older versions

2021-02-10 15:43 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +Let us say user1 issues a read query, and user2 issues a write that changes the result that the first read query would get.
It is important to note that in come cases read-after-write consistency can be lost.

For example, if user1 issues a read query and user2 issues a write, that changes the result that the first read query would get, then user2 issues an identical read while user1's read is still executing.

In this case the consolidator will kick in and user2 will get the result of user1's query thereby losing read-after-write consistency.

2021-02-10 15:43 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +If the application is sensitive to this behavior then you can specify that consolidation should be disabled on the primary, i.e., `-enable_consolidator=false` and `-enable_consolidator_replica=true`
If the application is sensitive to this behavior, then you can specify that consolidation should be disabled on the primary using the following flags: `-enable_consolidator=false` and `-enable_consolidator_replica=true`.

2021-02-11 00:16 UTC, deepthi commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +* `-enable_consolidator`: Defaults to true.
I couldn't see the difference. What am I missing?

2021-02-11 00:22 UTC, deepthi commented
Thanks @hallaroo. I have accepted your suggestions except for the `Flags` section where I can't see the difference.

2021-02-11 00:44 UTC, deepthi commented on content/en/docs/user-guides/configuration-advanced/query-consolidation.md
> +* `-enable_consolidator`: Defaults to true.
Added newline per chat with @hallaroo

2021-02-11 16:04 UTC, hallaroo approved these changes

2021-02-11 16:05 UTC, merged