Tablet throttler: custom queries and threahold
vitessio/website pull request #729
Opened 2021-03-21 12:12 UTC by shlomi-noach

Documenting the changes in https://github.com/vitessio/vitess/pull/7541

This documentation change explains how to configure custom throttler queries and threshold, and the use of `-throttle_check_as_check_self`.

2021-03-21 12:14 UTC, shlomi-noach commented
Preview for specific change in this PR: https://deploy-preview-729--vitess.netlify.app/docs/reference/features/tablet-throttler/#custom-metrics--queries

2021-03-22 14:50 UTC, hallaroo requested changes
I had a couple grammar/link changes, but will leave @aquarapid to review the content. Thanks!

2021-03-22 14:50 UTC, hallaroo commented on content/en/docs/reference/features/tablet-throttler.md
> +VTTablet runs a cooperative throttling service. This service probes the shard's MySQL topology and observes health, measure by replication lag, or by other metric delivered by custom query, on server
VTTablet runs a cooperative throttling service. This service probes the shard's MySQL topology and observes health, measured by replication lag, or by another metric delivered by custom query, on servers.

2021-03-22 14:50 UTC, hallaroo commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess only supports gauges for custom metrics: the user may define a query which returns a gauge value, an absolute metric by which Vitess can throttle. See #configuration, below.
See `[#configuration](../#configuration) `below.

2021-03-22 14:50 UTC, hallaroo commented on content/en/docs/reference/features/tablet-throttler.md
> +- To override default lag evaluation, and measure a different metric, use `-throttle_metrics_query`. The query must be either of these forms:
To override the default lag evaluation, and measure a different metric, use `-throttle_metrics_query`.

2021-03-25 06:43 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +- To override default lag evaluation, and measure a different metric, use `-throttle_metrics_query`. The query must be either of these forms:
fixed

2021-03-25 06:43 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +Vitess only supports gauges for custom metrics: the user may define a query which returns a gauge value, an absolute metric by which Vitess can throttle. See #configuration, below.
fixed

2021-03-25 06:43 UTC, shlomi-noach commented on content/en/docs/reference/features/tablet-throttler.md
> +VTTablet runs a cooperative throttling service. This service probes the shard's MySQL topology and observes health, measure by replication lag, or by other metric delivered by custom query, on server
fixed

2021-03-25 14:08 UTC, hallaroo approved these changes
LGTM!

2021-03-25 14:10 UTC, hallaroo commented
I don't know if we want to wait for anyone else to review the content, but I'm happy to merge if my review is enough. Thanks!

2021-03-26 12:51 UTC, rohit-nayak-ps approved these changes
lgtm

2021-03-26 12:52 UTC, merged