Initial transfer of Examining query plans in MySQL and Vitess Blog
vitessio/website pull request #817
Opened 2021-08-30 08:59 UTC by askdba

Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>

2021-08-30 09:30 UTC, shlomi-noach requested changes

2021-08-30 09:30 UTC, shlomi-noach commented on content/en/blog/2021-09-02-examine-query-plan.md
> +Originally posted at [link](http://systay.github.io/2021/08/27/explain-a-query.htm)
replace "link" with a descriptive name.

2021-08-30 09:30 UTC, shlomi-noach commented on content/en/blog/2021-09-02-examine-query-plan.md
> +Traditional query optimizing is mostly about two things: first - in which order and from where to access data, and then how to then combine it.
"first" is followed by a dash, "second" is not. I'd suggest replace dash with comma.

2021-08-30 09:30 UTC, shlomi-noach commented on content/en/blog/2021-09-02-examine-query-plan.md
> +Here we can see that the MySQL optimizer things the best plan is to start reading from `t1` using a table scan. It could have used an index, but since we are projecting every column `(SELECT *)`, it’
```suggestion
Here we can see that the MySQL optimizer thinks the best plan is to start reading from `t1` using a table scan. It could have used an index, but since we are projecting every column `(SELECT *)`, it’s reading the full table.
```

2021-08-30 09:30 UTC, shlomi-noach commented on content/en/blog/2021-09-02-examine-query-plan.md
> +This is hashed in the next step, and we know it is hashing on the `c1` column. This is then read by the hash join step, which will use the hash map to join data from `t1` and `t2` using the `t2.c1 =
duplicate paragraph?
```suggestion
```

2021-08-30 09:30 UTC, shlomi-noach commented on content/en/blog/2021-09-02-examine-query-plan.md
> +Next we need to hash the results again, and this time the probe table (that’s what the hash map is called) is used to join with `t3`.
still unsure what the probe table is. Perhaps quote it, the "probe" table, to highlight that it's an internal term? Or better, introduce us to probe tables?

2021-08-30 10:20 UTC, askdba commented on content/en/blog/2021-09-02-examine-query-plan.md
> +Next we need to hash the results again, and this time the probe table (that’s what the hash map is called) is used to join with `t3`.
@systay, please clarify here.

2021-08-31 14:58 UTC, systay commented on content/en/blog/2021-09-02-examine-query-plan.md
> +Next we need to hash the results again, and this time the probe table (that’s what the hash map is called) is used to join with `t3`.
removed the mention of probe table. no need to go deep into how a hash join works here

2021-08-31 15:15 UTC, askdba reviewed
LGTM

2021-08-31 15:34 UTC, shlomi-noach approved these changes

2021-08-31 15:47 UTC, askdba commented
Do not merge, this will go out on 9/2/2021.

2021-08-31 15:48 UTC, systay commented
thanks for the review, @shlomi-noach. I'll copy the changes to my personal blog as well :bow:

2021-09-04 04:40 UTC, askdba commented
Do not merge, set to out 9/7/2021 due to long weekend.

2021-09-07 07:41 UTC, merged