Adding new user guides
vitessio/website pull request #837
Opened 2021-09-30 22:02 UTC by hallaroo

2021-10-04 14:41 UTC, Anders-PlanetScale requested changes
There are a few minor changes needed.

For the v2 ReverseTraffic commands REPLICA and PRIMARY example commands drop the -dry_run flag, where all other v2 examples contain it. We should add it.

Line 513 and line 519:
vtctlclient -server vtctld.host:15999 MoveTables -tablet_types=replica ReverseTraffic targetkeyspace.workflowname

and 

vtctlclient -server vtctld.host:15999 MoveTables -tablet_types=primary ReverseTraffic targetkeyspace.workflowname

The v1 reverse traffic commands look incorrect, the output examples after the original examples look correct.

These start at line 535.

2021-10-04 19:37 UTC, aquarapid requested changes, later dismissed

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> +  For example, the affected rows variable returned by the MySQL protocol becomes the number of rows matched by the `WHERE` clause instead.
Let's make this: 

```For example, the `affected_rows` field return by the MySQL protocol (https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html) becomes the number of rows matched by the `WHERE` clause instead.```

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> +  * Used by vttablet `ExecuteFetchAsDba` RPC.
Add to this line:  This is used when using `vtctlclient ExecuteFetchAsDba`

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> +  * Used by vttablet `ExecuteFetchAsApp` RPC.
Add to this line: This is used when using `vtctlclient ExecuteFetchAsApp`

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> + * Hardcoded (default 3)
Let's make this:  Hardcoded (size 3)

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> + * Hardcoded (default 3)
Let's make this: Hardcoded (size 3)

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> + * Used in Online DDL to measure/track the master -> replica lag, and adjust the DDL copy speed accordingly.
s/master/primary/

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> + * Created on demand by `ExecuteFetchAsAllPrivs`
Rather:  Created on demand by `vtctlclient ExecuteFetchAsAllPrivs`

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> + * Used to setup MySQL replication between shard master and replica instance types.
s/master/primary/

2021-10-04 19:37 UTC, aquarapid commented on content/en/docs/reference/features/connection-pools.md
> + Or disable this limit feature by setting `-transaction_limit_by_username` to `false` as the default is `true`.
Add:  This option only comes into play if the TX limiter is enabled by `-enable_transaction_limit`, which it is not by default.

2021-10-05 19:23 UTC, Anders-PlanetScale approved these changes
Changes look good.

2021-10-05 20:24 UTC, gedgar requested changes, later dismissed
Looks good, spare some minor nits

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/reference/features/connection-pools.md
> +In older Vitess versions, some pools would eventually shrink again, but in recent Vitess versions a new pool connection is created when an old one reaches its idle timeout.
Might be helpful if we added the specific Vitess version which introduced this change?

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +- With Vitess versions before v10, be careful of making the row and packet buffers too large, since you might run an issue where [vreplication catchup mode may be unable to terminate](https://github.
'since you might run an issue' -> 'as you may run into an issue'

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +If you do plan to execute another VDiff that will get the workflow back to the proper state.
We could use a comma after VDiff,

or reworded a bit: 
Executing another VDiff immediately afterwards will return the workflow back to the proper state.

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +If you do NOT plan to execute another VDiff you will need to double check the current state of the workflow to ensure that it’s running after you interrupted the vtctlclient process.
Comma after VDiff

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +If the workflow state is STOPPED and the message field is empty then you can simply start the workflow again:
comma after empty
also could 'then'

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +vtctlclient -server ...  ApplyRoutingRules -rules=($cat /path/to/save/routingrules.json) -dry-run
($cat /path/to/save/routingrules.json) ->
"$(cat /path/to/save/routingrules.json)"

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +4. Once you have verified the command works as intended run it without -dry-run:
comma after intended
maybe change run to rerun

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +Some Vreplication workflows (e.g. MoveTables and Resharding) have their own DropSources cleanup command, which can take care of much of the above.
s/Vreplication/VReplication

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +With MoveTables v2 instead of performing SwitchReads/Writes you will use MoveTables --SwitchTraffic.
comma after v2

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +1. Depending on what `-table_type` you are using you will use one of the four following commands:
comma after using

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +After you have tried the above command(s) with `-dry_run` remove just that flag to then actually run the command.
Maybe change to:

After you have tried the above command(s), remove the `-dry_run` flag to actually execute them.

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +1. Depending on what `-table_type` you are using you will use one of the two following commands:
comma after using

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> + After you have tried the above command(s) with `-dry_run` remove just that flag to then actually run the command.
same as above; maybe change to:

After you have tried the above command(s), remove the `-dry_run` flag to actually execute them.

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +After you have tried the above command(s) with `-dry_run` remove just that flag to then actually run the command.
Maybe change to:

After you have tried the above command(s), remove the `-dry_run` flag to then actually execute them.

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +If the vreplication of changes from the sourcekeyspace to the targetkeyspace are lagging (possibly because of high write rate to the source keyspace), the SwitchWrites operation may fail.
VReplication

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +1. Depending on what `-table_type` you are using you will use one of the four following commands:
comma after using

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +1. Depending on what `-table_type` you are using you will use one of the two following commands:
comma after using

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +1. Depending on what `-table_type` you are using you will use one of the two following commands:
comma after using

2021-10-05 20:24 UTC, gedgar commented on content/en/docs/user-guides/migration/cutover.md
> +2. After the reads are switched you will then need to reverse the writes
comma after switched
missing colon after writes

2021-10-05 22:31 UTC, hallaroo commented on content/en/docs/reference/features/connection-pools.md
> +In older Vitess versions, some pools would eventually shrink again, but in recent Vitess versions a new pool connection is created when an old one reaches its idle timeout.
I'm actually not sure what version this change was in. I'll see if I can track that down.

2021-10-07 20:54 UTC, hallaroo commented on content/en/docs/reference/features/connection-pools.md
> +In older Vitess versions, some pools would eventually shrink again, but in recent Vitess versions a new pool connection is created when an old one reaches its idle timeout.
And @aquarapid tracked that down in no time flat. This should be fixed.

2021-10-07 21:33 UTC, merged