Update docs for ers
vitessio/website pull request #844
Opened 2021-10-13 12:06 UTC by GuptaManan100

This PR updates the docs for ERS reflecting the changes in https://github.com/vitessio/vitess/pull/8492

2021-10-13 15:25 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/reparenting.md
> +As such, this command does not rely on the current master at all to replicate data to the new master. Instead, it makes sure that the master-elect is the most advanced in replication within all of th
As such, this command does not rely on the current master at all to replicate data to the new master. Instead, it makes sure that the master-elect is the most advanced in replication within all of the available replicas or that the master-elect has caught up to the most advanced one. In either case, the candidate will only be promoted once it is the most advanced replica.

2021-10-13 15:26 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/reparenting.md
> +As such, this command does not rely on the current master at all to replicate data to the new master. Instead, it makes sure that the master-elect is the most advanced in replication within all of th
Also do we need to change master to primary?

2021-10-13 15:27 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/reparenting.md
> +3. Wait for the primary-elect to catch up to the most advanced replica if itsn't already the most advanced.
3. Wait for the primary-elect to catch up to the most advanced replica, if it isn't already the most advanced.

2021-10-13 18:03 UTC, hallaroo requested changes
Added a couple suggestions on wording updates and one question on if we need to change master to primary for this part of the doc. Thanks!

2021-10-14 05:02 UTC, GuptaManan100 commented on content/en/docs/user-guides/configuration-advanced/reparenting.md
> +As such, this command does not rely on the current master at all to replicate data to the new master. Instead, it makes sure that the master-elect is the most advanced in replication within all of th
i am going to change master to primary as a separate PR since it is there in more commands other than ERS too

2021-10-14 12:38 UTC, GuptaManan100 commented on content/en/docs/user-guides/configuration-advanced/reparenting.md
> +As such, this command does not rely on the current master at all to replicate data to the new master. Instead, it makes sure that the master-elect is the most advanced in replication within all of th
it seems that change was already made and I was on an old version of prod when I started working. Merging prod has gotten rid of those master references

2021-10-14 12:40 UTC, GuptaManan100 commented
This is getting too polluted. The branch was based against an old version of prod and has a bunch of merge conflicts. I did not handle them correctly. I am going to close this and create a new one instead

2021-10-14 12:40 UTC, closed without merging

2021-10-14 12:48 UTC, GuptaManan100 commented
Succeeded by #845