adding in info on vttablet idle-timeout
vitessio/website pull request #850
Opened 2021-10-22 16:48 UTC by hallaroo

2021-11-02 03:20 UTC, aquarapid requested changes

2021-11-02 03:20 UTC, aquarapid commented on content/en/docs/user-guides/configuration-basic/vttablet-mysql.md
> +* `queryserver-config-idle-timeout`:  This value sets a time in seconds after which, if a connection has not been used, this connection will be removed from pool. This effectively manages number of c
from **the** pool?

2021-11-02 03:20 UTC, aquarapid commented on content/en/docs/user-guides/configuration-basic/vttablet-mysql.md
> +* `queryserver-config-idle-timeout`:  This value sets a time in seconds after which, if a connection has not been used, this connection will be removed from pool. This effectively manages number of c
Let's drop the second sentence.  In newer versions, we refill the pool immediately, so it doesn't actually reduce the number of connections in the pool.

2021-11-02 03:20 UTC, aquarapid commented on content/en/docs/user-guides/configuration-basic/vttablet-mysql.md
> +	* This is because MySQL's `wait_timeout` is the number of seconds the server waits for activity on a noninteractive connection before closing it. So if the vttablet setting is not lower the MySQL li
Let's add another bullet point about how if you are using `-enable_system_settings` (ref the relevant section on the new reserved connections page from PR #862 ), you should also make sure your `max_connections` are set high enough (maybe even higher than otherwise).

2021-11-03 23:25 UTC, aquarapid approved these changes
I pushed two changes, I think it's good now.  You just need to resolve the conflict.

2021-11-10 21:37 UTC, closed without merging

2021-11-10 21:37 UTC, hallaroo commented
Fixed this by cherry picking the commits I needed to a new branch. https://github.com/vitessio/website/pull/873