Adding multi-cell topology information
vitessio/website pull request #877
Opened 2021-11-12 23:21 UTC by FancyFane

Adding additional clarification around configuring global and local topology services on different processes. This should assist users when creating multi-cell environments. 

Signed-off-by: FancyFane <fane@planetscale.com>

2021-11-15 18:29 UTC, FancyFane commented
This section could use additional clean up, and maybe even divide up the pages a bit more, but I'll mark this as "Ready for Review" for now, and we can create a new pull request for additional cleanup.

2021-11-17 20:55 UTC, mattlord requested changes
Looking good! I left some minor comments and suggestions, let me know when you want me to do another pass.

Thank you! ❤️

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +* Create the global keystore service using etcd, zookeeper, or consul.
We should be careful with terms as there's already enough to keep straight. We should use "global topology service" instead of "global keystone service".

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +topology to the global topology. At a higher level overview:
nit, but we're defining the local cell in the global topology (we define the name, the topo server, and root path for the cell).

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +* Use vtctld command to initialize it as the global topology service. NOTE: for
I would say `vtctl client command` here. `vtctl` is the stand-alone client and server combined, whereas `vtctlclient` is the client that works with a `vtctld` server. vtctld has a web UI (for humans) and a gRPC endpoint for clients (primarily vtctlclient).

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +* Use vtctld command to initialize it as the global topology service. NOTE: for
We often use vtctl as a short hand for vtctl/vtctlclient as they contain the same client code and commands, vtctlclient just needs to have a vtctld server provided for the server side.

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +* For each cell create a local keystore service using a separate instance of
Again,`s/keystore/topology/g`

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +  information, as well as the name of the cell. The information on the local
To be clear, I would say the name of the cell where that component (vttablet, vtgate, etc) will live.

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +  cell topology will be passed to the process from the global topology service
Nit, but I would say it will be read from the global topology service as the caller will request it via "cells_to_watch" (vtgate will often watch all of them whereas a vttablet only cares about its own cell -- which is why you must use a cell alias for multi-cell tablet driven operations like MoveTables).

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +2. Associate vtctld to the etcd service and initialize global topology values
Nit, but I would say tell vtctld to use the global topology server (there's not really anything to write yet as we have no keyspaces or cells). Whether or not the global root gets created head of time is implementation dependent (since it's really only a key prefix).

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +CELL_TOKEN="SOMETHING_UNIQ_HERE_TOO"
This is just a unique identifier for participating processes, so I'd suggest cell name.

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +4. Register the local etcd service to the global topology service using vtctl or
Nit but I would say that we're defining the cell and its associated local topology service in the global topology service.

We are also slowly moving away from vtctl to vtctlclient and the only difference between them here is whether you specify the VTCTLD endpoint info or the TOPOSERVER endpoint info. So I'd just use the vtctlclient example to simplify things.

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +TAB_NAME=${CELL_NAME}-100
This is where you define the cell for the vttablet, FWIW. Whereas vtgate has an explicit cell flag.

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +TAB_NAME=${CELL_NAME}-100
I would also call it `TABLET_ALIAS` as that's what it is in the product, and it consists of two parts:
${CELL}-${TABLET_UID} (UID must be unique within the cell and the alias must be unique in the cluster)

2021-11-17 20:55 UTC, mattlord commented on content/en/docs/reference/features/topology-service.md
> +6. You can repeat steps 3 through 5 above to create each cell as needed. If you
RebuildKeyspaceGraph is for vtgates and their serving graph (exposed via mysql> `SHOW VITESS_TABLETS`)

RebuildVSchemaGraph will propagate the vschema from the global topology service to the local topology services in their SrvVSchema. Not sure how best to express this here w/o adding confusing, but noting it. We could at least know that we're ensuring the local topology servers are up to date by propagating the latest info in the global service.

2021-11-19 16:15 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +* Create the global keystore service using etcd, zookeeper, or consul.
I agree, in my mind I was trying to think of what we call the backend service (etcd, zk, and consul) BEFORE it gets stamped/configured with the global topology information for Vitess. I'll work on cleaning up things a bit more here.

2021-11-19 16:21 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +4. Register the local etcd service to the global topology service using vtctl or
Thank you Matt, when looking at this I could see both vtctl and the vtctlclient as similar in nature. Knowing the context of where Vitess was and where it is going I'll keep the vtctlclient examples.

2021-11-19 16:27 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +6. You can repeat steps 3 through 5 above to create each cell as needed. If you
When I was working with discrete global/local instances, I came across the issue of not having up-to-date serving graph information on the vtgate, and noted Sugu's comment on this [blog entry](https://vitess.io/blog/2020-04-27-life-of-a-cluster/#understanding-keyspaces-and-shards). I figured it may be better to make a note of it here as well, in the event others had this problem.

2021-11-19 17:46 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +* Create the global keystore service using etcd, zookeeper, or consul.
@mattlord can you let me know what you think of the new wording here? I'm trying to be explicitly clear that we need a keystore service (etcd, zk, or consul) BEFORE we can have topology service. Can you let me know your thoughts here?

I tried to follow the use of the word `keystore` with `(etcd, zookeeper, consul)`

```## Running multi cell environments

When running an environment with multiple cells, it is essential to first create
and configure your global topology service. Then define each local topology
service to the global topology. As mentioned perviously, the global
and local topology service can reside on the same or sperate keystore
(etcd, zookeeper, or consul) implementations. At a higher level overview:

* Create or locate an existing keystore (etcd, zookeeper, or consul) for the
  global keystore service.
* Use vtctl client commands to initialize the global topology service,
  providing the keystore implementation, address, and root directory.
  NOTE: for best practices the root dir should be set to `/vitess/global`.
* (Optional) For each cell create a keystore (etcd, zookeeper, or consul) for
  the local topology service. This step is optional as you may use the existing
  keystore implementation used by the global topology service. NOTE: the 
  keystore technologies must match. For example, if you are using zookeeper for
  your global topology service then you must use zookeeper for your local
  topology service. You can not mix and match.
* For each cell, using vtctl client commands, define the local topology service
  with the global topology service. This is done by providing the three
  elements: the cell name, the local keystore address/port, and the root
  directory. NOTE: for best practices the local root dir should be set to
  `/vitess/${CELL_NAME}` where ${CELL_NAME} is the location of the cell;
  `us-west-2`, `us-east-1`, etc.
* When starting vtgate/vttablet services, you will provide the global topology
  information, as well as the cell name. The global topology service will do
  a lookup on the cell name, to find and provide the local topology details back
  to the vtgate/vttablet process.

2021-11-19 19:40 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +* Create the global keystore service using etcd, zookeeper, or consul.
Resolved by simply referring to these services as "instance" when a general word was needed. This was done previously in the document.

2021-11-19 19:41 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +topology to the global topology. At a higher level overview:
s/register/define/g

2021-11-19 19:43 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +* Use vtctld command to initialize it as the global topology service. NOTE: for
Updated to say "vtctl client commands" and leave open for end user to determine which one to use. Example commands later in the document will just use `vtctlclient`.

2021-11-19 19:44 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +* For each cell create a local keystore service using a separate instance of
Done. Also did a "Ctrl+F" search for "keystore" to ensure that term is not being introduced in this document. Thank you for the clarification here.

2021-11-19 19:44 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +  information, as well as the name of the cell. The information on the local
I agree, and have added example names based on AWS locations to give the reader some hints here.

2021-11-19 19:47 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +  cell topology will be passed to the process from the global topology service
Upon reading your notes and reflecting a bit more, I've separated this out, so we can discuss vtgate and vttablet independently. Also, added a note about the potential for vtgate to watch more than one cell and thus more than one local topology service.

2021-11-19 19:48 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +  cell topology will be passed to the process from the global topology service
I did not include a note about the `MoveTables` operation as it may be outside the scope of this document.

2021-11-19 19:51 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +2. Associate vtctld to the etcd service and initialize global topology values
I wrote it this way from local testing and seeing vtctld updating values once this command is ran. After you've provided clarification I re-wrote this step, to just say vtctld is simply using the global topology service created in step 1.

2021-11-19 19:52 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +CELL_TOKEN="SOMETHING_UNIQ_HERE_TOO"
Not a bad idea, as cell names should be unique. Implemented.

2021-11-19 19:54 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +4. Register the local etcd service to the global topology service using vtctl or
s/register/define/g

Also, removed the `vtctl` example, so we can steer our readers towards using `vtctlclient`.

2021-11-19 20:11 UTC, FancyFane commented on content/en/docs/reference/features/topology-service.md
> +TAB_NAME=${CELL_NAME}-100
Thank you, I've made this change as well as add some additional documentation on these variables. I've split out step 5 into two step 5s so we can clarify some of the differences between vtgate and vttablet.

2021-11-19 20:22 UTC, FancyFane commented
Upon editing this document, I've also realized we have several variables called `TOPOLOGY` while discussing both local and global topology services. To help ensure clarity I've renamed these variables to `GLOBAL_TOPOLOGY`.

2021-11-19 22:20 UTC, mattlord approved these changes
Thanks, @FancyFane ! ❤️

2021-11-22 19:14 UTC, merged