VTGate Buffering Documentation
vitessio/website pull request #916
Opened 2021-12-21 00:04 UTC by FancyFane

Signed-off-by: FancyFane <fane@planetscale.com>

Buffering documentation draft, still need to iterate though the examples and ensure the results are consistent.

2021-12-22 22:07 UTC, hallaroo requested changes
A few formatting/capitalization/grammar things

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +eliminate, downtime during planned fail overs  PlannedReparentShard (PRS)
eliminate, downtime during planned fail overs PlannedReparentShard (PRS) 

-had an extra space

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +operations.  It has been extended to provide buffering in some additional fail
- Remove operations
- VTGate has been extended

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +Note that buffering is not intended for, or active during, unplanned failovers
Note that buffering is not intended for, nor is active during, unplanned failovers

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +There are some new heuristics built with the `keyspace_events` implementation
There are some new heuristics built in the `keyspace_events` implementation for scenarios where the `PRIMARY`is offline. However, you should not rely on these new heuristics at this time.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +As you may imagine if you think about the problem, buffering can be
Buffering can be somewhat involved and there are a number of tricky edge cases.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +discuss this in the context of an application's experience, starting with
discuss these edge cases in the context of an application's experience, starting with the simplest case: that of buffering during a PRS (PlannedReparentShard).

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +buffering:
new line between buffering: and * `-enable_buffer` for formatting please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +  for longer than this from when the first request was buffered, stop buffering
If buffering is active longer than this time starting from when the first request was buffered, stop buffering

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +  fail overs, and makes sure that the application will eventually receive
This avoids "endless" buffering if there are consecutive fail overs. It makes sure that the application will eventually receive errors that will allow it (or the application client) to take appropriate action within a bounded amount of time.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +Fundamentally Vitess will:
New line between 72 and 73 please! Just for formatting

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> + * Hold up and buffering queries to the `PRIMARY` tablet for a shard.
Hold up any buffering queries to the `PRIMARY` tablet for a shard.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +Simplifying considerably:
New line between 91 and 92 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +Simplifying considerably:
The following steps are considerably simplified, but give a high level overview of how buffering works:

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +  e.g. if an individual request was buffered for too long;  or if buffering
e.g. if an individual request was buffered for too long; or if buffering

- extra space

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +## Potential Errors
New line between 122 and 123 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +Buffering was implemented to minimize downtime, there are still potential for
Buffering was implemented to minimize downtime, but there is still potential for

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +### Lost connection
New line between 127 and 128 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +Due the nature of buffering and pausing your queries the MySQL client will see
Due to the nature of buffering and pausing your queries the MySQL client will see

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +`write_timeout` set the value should be greater than the value set
`write_timeout` set, the value should be greater than the value set for

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +```
New line between 139 and 140 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +this result in the application for a variety of reasons:
New line between 145 and 146 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +PRS event is being executed on
* `buffer_keyspace_shards` is not configured for the keyspace on which the
PRS event is being executed

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/reference/features/vtgate-buffering.md
> +## Next Steps
New line between 158 and 159 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +In this wiki we are going to go through a few scenarios involving buffering to
In this guide we are going to go through a few scenarios involving buffering to

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +windows for these exercises:
New line between 14 and 15 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +These scenarios will be will be using a Vitess Release 13 SNAPSHOT, and will be
These scenarios will be using a Vitess Release 13 SNAPSHOT, and will be

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Terminal 1
New line between 33 and 34 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +2.) Locate the vtgate process; copy the process information to your notes for
Locate the vtgate process, copy the process information to your notes for future use, and then kill the process:

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +3.) From your notes, paste in the vtgate command you have previously copied back
From your notes, paste in the vtgate command you have previously copied into the terminal window:

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Terminal 2:
New line between 72 and 73 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +be used to simulate traffic on vitess. The virtualenv and source commands are
be used to simulate traffic on Vitess.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Terminal 3:
New line between 99 and 100 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +PlannedReparentShard (PRS) operation. Note, `time` is optional but it is useful
PlannedReparentShard (PRS).

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 121 and 122 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 122 and 123 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 128 and 129 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +NOTE: reviewing the buffered request metrics from vtgate, nothing was buffered
New line between 150 and 151 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +### Scenario 2: Solving with error Handling
New line between 154 and 155 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +(5000ms) waiting for a `PRIMARY` tablet to return.
(5000ms) for a `PRIMARY` tablet to return.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 164 and 165 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +As soon as traffic is sent issue the PlannedReparentShard command:
New line between 165 and 166 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 171 and 172 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +error. The error is displayed on screen, and the application sleeps for 5
error. The error is displayed on screen and the application sleeps for 5

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 191 and 192 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +### Scenario 3: Solving with Buffering
New line between 195 and 196 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +First we will need to reconfigure vtgate running in your terminal 1.
New line between 201 and 202 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 205 and 206 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Add the vtgate arguments needed to implement buffering, we are only implementing
Add the vtgate arguments needed to implement buffering. We are only implementing

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 221 and 222 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 226 and 227 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +As soon as traffic is sent issue the PlannedReparentShard command:
New line between 227 and 228 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 233 and 234 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Shortly after the PRS command is issued, the SQL statements pause momentarily,
Shortly after the PRS command is issued, the SQL statements will pause momentarily.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +also during this time a message is logged to the terminal console window:
During this time a message is also logged to the terminal console window:

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 258 and 259 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +### Scenario 4: Quickly issued PRS events
New line between 264 and 265 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Restart the vtgate process to clear metrics:
New line between 269 and 270 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 280 and 281 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 285 and 286 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +is a 5 second sleep commands between the PRS statements.
New line between 287 and 288 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 293 and 294 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Due to the close nature of these events, buffering is disabled to protect vitess
Due to the close nature of these events, buffering is disabled to protect Vitess

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +against events where PRS may be issued in looping fashion. This behavior is
against events where PRS may be issued in a looping fashion.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 312 and 313 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +NOTE: Here we will see the `LastFailoverTooRecent` to let us know these PRS
NOTE: Here we will see the `LastFailoverTooRecent` error to let us know these PRS

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Preventing this issue
New line between 317 and 318 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +We can prevent this issue by implementing error handling which your application
We can prevent this issue by implementing error handling, which your application

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +### Scenario 5: Too many connections
New line between 325 and 326 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Restart the vtgate process to clear metrics:
New line between 331 and 332 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 349 and 350 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 355 and 356 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +the estimated amount of request you'll get during the PRS event.
the estimated amount of requests you expect to get during the PRS event.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 374 and 375 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +NOTE: Here we will see the `LastFailoverTooRecent` to let us know these PRS
or metric? I'm not sure which word is best here

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +### Scenario 6: Buffer time too Short
New line between 379 and 380 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +In this scenario we are going to set the buffer_window to a short period of time,
In this scenario we are going to set the `buffer_window` to a short period of time

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Restart the vtgate process to clear metrics:
New line between 383 and 384 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 401 and 402 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 407 and 408 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +In these results, we see a few SQL statements fail to buffer, while they display
In these results, we see a few SQL statements fail to buffer. They display

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 424 and 423 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +informing us the buffer_window was not long enough for these request.
informing us the `buffer_window` was not long enough for these requests.

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +### Scenario LAST: Replica never becomes Primary
New line between 430 and 431 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Here we will tear down the cluster, install an older version of mysql, and rebuild
New line between 441 and 442 please!

And

Here we will tear down the cluster, install an older version of mysql, and rebuild:

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 467 and 468 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +As soon as the heavy traffic starts to generate send the PRS command.
New line between 468 and 469 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +#### Results:
New line between 474 and 475 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +Part of the reason we had to downgrade mysql was to make replication issues more
Part of the reason we had to downgrade MySQL was to make replication issues more

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 501 and 502 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +There are a few things we can do to resolve this issue:
New line between 502 and 503 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +This scenario was designed to show buffering assisting
This scenario was designed to show buffering assisting:

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +```
New line between 522 and 523 please!

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +buffer_window to cover these failures. Retrying this scenario with the following
`buffer_window` to cover these failures. Retrying this scenario with the following

2021-12-22 22:07 UTC, hallaroo commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +then rebuild the vitess cluster:
New line between 533 and 534 please!

2021-12-23 18:25 UTC, FancyFane commented on content/en/docs/reference/features/vtgate-buffering.md
> +  for longer than this from when the first request was buffered, stop buffering
Even with this adjustment it was still a bit weird, so I've reworded this further: 
`If buffering is active longer than this set duration, stop buffering and return errors to the client.`

2021-12-23 18:46 UTC, FancyFane commented on content/en/docs/reference/features/vtgate-buffering.md
> +  fail overs, and makes sure that the application will eventually receive
This was still worded a bit weird with the edits. I've removed these sentences and re-worded the message entirely:

```
 * `-buffer_min_time_between_failover`: Default `1m`. If consecutive
  fail overs for a shard happens within less than this duration, do **not**
  buffer again. The purpose of this setting is to avoid consecutive fail over 
  events where vtgate may be buffering, but never purging the buffer.```

2021-12-23 18:49 UTC, FancyFane commented on content/en/docs/reference/features/vtgate-buffering.md
> + * Hold up and buffering queries to the `PRIMARY` tablet for a shard.
Reworded as:
* Hold up and buffer any queries sent to the `PRIMARY` tablet for a shard.

I do believe `and` is correct here but the sentence did need some re-working to make sense.

2021-12-23 22:17 UTC, FancyFane commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +NOTE: Here we will see the `LastFailoverTooRecent` to let us know these PRS
metric is the more correct noun to use here.

2021-12-23 22:50 UTC, FancyFane commented on content/en/docs/user-guides/configuration-advanced/buffering-scenarios.md
> +This scenario was designed to show buffering assisting
This sentence was an incomplete thought, and you picked up on it; I've added more information here:

```
This scenario was designed to show buffering assisting, even during a failed
PlannedReparentShard:```

2021-12-23 23:30 UTC, FancyFane commented
I'm going to save a copy of the modified files, then do a pull request against the new versioned documentation. I think it'll make this cleaner. I've implemented changes from @hallaroo. For now I will close this out.

2021-12-23 23:30 UTC, closed without merging