Document the usage of PlannedReparentShard with init_db.sql file
vitessio/website pull request #948
Opened 2022-01-22 13:32 UTC by GuptaManan100

Release 13 onwards, we will be able to use PlannedReparentShard to initialise the cluster even with a `init_db.sql` file as long as no errant GTIDs are produced. This PR documents that scenario.

2022-01-24 18:06 UTC, hallaroo requested changes
Adjusting a bit for readability.

2022-01-24 18:06 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/initialize-shard-primary.md
> +InitShardPrimary must be used in case the users are using a custom `init_db.sql` file in their setup which creates errant GTIDs on the vttablets. If the users have `SET sql_log_bin = 0` in the beginn
InitShardPrimary must be used when you add a custom `init_db.sql` file that creates errant GTIDs on vttablets to your setup. If you have `SET sql_log_bin = 0` at the beginning of your file (like in the example `init_db.sql` file), then PlannedReparentShard will work as expected and it should be used.

2022-01-25 02:35 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/initialize-shard-primary.md
> +InitShardPrimary must be used in case the users are using a custom `init_db.sql` file in their setup which creates errant GTIDs on the vttablets. If the users have `SET sql_log_bin = 0` in the beginn
Let's make this absolutely clear.. Something like
```
If using a custom `init_db.sql` that omits `SET sql_log_bin = 0`, then InitShardPrimary must be used instead of PlannedReparentShard.
```

2022-01-25 15:35 UTC, hallaroo approved these changes
LGTM!

2022-01-25 15:38 UTC, merged