Add docs for the durability policies
vitessio/website pull request #955
Opened 2022-01-27 11:46 UTC by GuptaManan100

This PR adds the documentation for the durability policies which are part of vtctl, vtctld, vtworker and vtorc. It also documents its usage for logging discrepancies in semi-sync setup as introduced in https://github.com/vitessio/vitess/pull/9533

2022-01-27 23:18 UTC, hallaroo requested changes, later dismissed
A few grammar changes and one link insert suggestion.

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +Vitess now supports a configurable interface for the durability policies. The users can now define in the interface which tablets are eligible to be promoted to a PRIMARY instance. They can also spec
Vitess now supports a configurable interface for durability policies. Users can now define, in the interface, which tablets are eligible to be promoted to a PRIMARY instance.

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +The interface definition looks like -
The interface definition looks like:

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +There are 3 implementations bundled with Vitess -
There are 3 implementations bundled with Vitess:

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> + - ***semi_sync*** - This durability policy setups the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers to acknowledge semi sync. It returns NeutralPromoteRul
This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers to acknowledge semi sync. It returns NeutralPromoteRule for Primary and Replica tablet types, MustNotPromoteRule for everything else

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> + - ***cross_cell*** - This durability policy setups the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This
This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This means that a transaction must be in two cells for it to be acknowledged. It returns NeutralPromoteRule for Primary and Replica tablet types, MustNotPromoteRule for everything else

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +Currently the durability policies are not used to setup semi-sync in EmergencyReparentShard or PlannedReparentShard. All the RPCs are still using `-enable_semi_sync` flag on vttablet to setup semi-sy
All the RPCs are still using the `-enable_semi_sync` flag on vttablet to setup semi-sync.

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +In case the user notices any logs that look like the following, they should create an issue and report it -
In case you notice any logs that look like the following, you should create an issue [here](https://github.com/vitessio/vitess/issues) and report it:

2022-01-27 23:18 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +If the following log is noticed when all the components are upgraded, then it should also be reported -
If the following log is noticed when all the components are upgraded, then it should also be reported:

2022-01-28 06:19 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +Vitess now supports a configurable interface for the durability policies. The users can now define in the interface which tablets are eligible to be promoted to a PRIMARY instance. They can also spec
Fixed

2022-01-28 06:19 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +The interface definition looks like -
Fixed

2022-01-28 06:19 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> + - ***semi_sync*** - This durability policy setups the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers to acknowledge semi sync. It returns NeutralPromoteRul
Fixed

2022-01-28 06:19 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> + - ***cross_cell*** - This durability policy setups the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This
Fixed

2022-01-28 06:20 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +Currently the durability policies are not used to setup semi-sync in EmergencyReparentShard or PlannedReparentShard. All the RPCs are still using `-enable_semi_sync` flag on vttablet to setup semi-sy
Fixed

2022-01-28 06:20 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +In case the user notices any logs that look like the following, they should create an issue and report it -
Fixed

2022-01-28 06:20 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +If the following log is noticed when all the components are upgraded, then it should also be reported -
Fixed

2022-02-01 00:36 UTC, deepthi approved these changes
Approving provisionally.
We can merge once feedback has been addressed.

2022-02-01 00:36 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
> +The new primary (if unspecified) is chosen using the [Durability Policies](../durability_policy) configured.
```suggestion
The new primary (if unspecified) is chosen using the configured [Durability Policy](../durability_policy). 
```

2022-02-01 00:36 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
> +The new primary (if unspecified) is chosen using the [Durability Policies](../durability_policy) configured.
Same as previous comment.

2022-02-01 00:36 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> + - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This me
```suggestion
 - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This means that a write must be in two cells for it to be acknowledged. It returns NeutralPromoteRule for Primary and Replica tablet types, MustNotPromoteRule for everything else
```

2022-02-01 00:36 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +```
This section still needs to change, right?
First thing people should do is check that their configuration on vtctld matches the config on vttablets, not create an issue.

2022-02-01 00:36 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/vtctld.md
> +Look at [Durability Policies](../durability_policy) for more information on the possible durability policies.
```suggestion
Look at [Durability Policies](../durability_policy) for more information on the available durability policies.
```

2022-02-01 00:36 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/vtorc.md
> +The `vtorc` config supports `Durability` setting. Look at [Durability Policies](../durability_policy) for more information on the possible durability policies.
```suggestion
The `vtorc` config supports `Durability` setting. Look at [Durability Policies](../durability_policy) for more information on the available durability policies.
```

2022-02-01 02:33 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +```
These logs only happen when someone has specified `-durability_policy=semi-sync` and then enableSemiSync isn't set on the tablet or we sent true for semi-sync for a non-primary eligible tablet. These bugs have to be reported, right?

2022-02-01 02:35 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
> +The new primary (if unspecified) is chosen using the [Durability Policies](../durability_policy) configured.
Fixed

2022-02-01 02:35 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
> +The new primary (if unspecified) is chosen using the [Durability Policies](../durability_policy) configured.
Fixed

2022-02-01 02:36 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> + - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This me
Fixed

2022-02-01 02:36 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/vtctld.md
> +Look at [Durability Policies](../durability_policy) for more information on the possible durability policies.
Fixed

2022-02-01 02:36 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/vtorc.md
> +The `vtorc` config supports `Durability` setting. Look at [Durability Policies](../durability_policy) for more information on the possible durability policies.
Fixed

2022-02-01 02:37 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +```
I'll add one more line asking for the users to verify that the vtctl configuration matches that of vttablet

2022-02-01 02:45 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> +```
I have made the requested change. If there is something else that needs change I'll create another PR for it. Merging this PR.

2022-02-02 16:38 UTC, merged