Document -max_transaction_lag_allowed flag
vitessio/website pull request #957
Opened 2022-01-30 13:43 UTC by rohit-nayak-ps

Document new flag implemented in https://github.com/vitessio/vitess/pull/9538
Signed-off-by: Rohit Nayak <rohit@planetscale.com>

2022-02-01 01:56 UTC, mattlord commented
As noted in the PR, I think we should use `-max_[v]replication_lag_allowed` as the name.

2022-02-01 02:04 UTC, mattlord requested changes

2022-02-01 02:04 UTC, mattlord commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +While switching traffic ensure that the VReplication lag for the workflow is less than this duration, otherwise
it's number of seconds, right? IMO, saying duration here may be confusing as many flags take a golang duration value like "5s" but here it would just be 5.

2022-02-01 02:04 UTC, mattlord commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +report an error and don't switch. VReplication lag is the estimated maximum lag across workflow streams between the last event seen at the source and the event processed by the target. Usually, when
IMO we should mention the heartbeat as well, e.g.: 
```
VReplication lag is the estimated maximum lag across workflow streams between the last event seen at the source and the last event processed by the target (which would be a heartbeat event if we're fully caught up).
```

2022-02-01 02:04 UTC, mattlord commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +While switching write traffic, we temporarily make the source databases read-only, and wait for the targets to catchup. The application will be down for this time: writes will error out. While switch
I would say ~ "write unavailability" instead of downtime.

2022-02-01 02:04 UTC, mattlord commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +This can also be useful if only reads are being switched: if the lag is too high the app might be reading stale data.
I would say something like:
```
While switching read traffic this can be used to set an approximate upper bound on how stale reads will be against the replica tablets when using `@replica` shard targeting.
```

2022-02-01 15:37 UTC, rohit-nayak-ps commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +While switching traffic ensure that the VReplication lag for the workflow is less than this duration, otherwise
It is a duration `maxReplicationLagAllowed := subFlags.Duration("max_replication_lag_allowed"`

2022-02-01 15:37 UTC, rohit-nayak-ps commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +report an error and don't switch. VReplication lag is the estimated maximum lag across workflow streams between the last event seen at the source and the event processed by the target. Usually, when
fixed as suggested

2022-02-01 15:37 UTC, rohit-nayak-ps commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +This can also be useful if only reads are being switched: if the lag is too high the app might be reading stale data.
fixed as suggested

2022-02-01 17:53 UTC, mattlord approved these changes

2022-02-01 17:54 UTC, mattlord commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +While switching traffic ensure that the VReplication lag for the workflow is less than this duration, otherwise
Ah, OK. So instead it's this that I think is confusing/misleading: https://github.com/vitessio/vitess/blob/6443bb502885dda91af6b5337e7bc682cb2861d9/go/vt/vtctl/vtctl.go#L2299

the "in seconds" part. No?

2022-02-02 06:37 UTC, mattlord requested changes
In addition to updating the flag name to `max_replication_lag_allowed`, could you please copy these changes to the new 14.0 versions of the pages?
- content/en/docs/14.0/reference/vreplication/flags.md
- content/en/docs/14.0/reference/vreplication/switchtraffic.md 

Those pages started as carbon copies of the 13.0 ones, so we can just copy them as-is to the 14.0 directory. 

Thank you!

2022-02-02 06:37 UTC, mattlord commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +#### -max_transaction_lag_allowed
We need to correct this to: `max_replication_lag_allowed`

2022-02-16 14:01 UTC, rohit-nayak-ps commented on content/en/docs/13.0/reference/vreplication/switchtraffic.md
> +While switching traffic ensure that the VReplication lag for the workflow is less than this duration, otherwise
Yes, the comment for the flag is incorrect, will fix in my next PR.

2022-02-16 19:11 UTC, mattlord approved these changes
Thanks!

2022-02-16 19:32 UTC, merged