vitess components flags update
vitessio/website pull request #960
Opened 2022-01-31 18:07 UTC by harshit-gangal

This PR updates the vitess components flag documents.

2022-01-31 19:03 UTC, deepthi reviewed
Thank you for taking this on, it needed to be done.
Did you generate these docs using a script?
Two main points:
- Previously some options were edited out by hand because they are not actually relevant for the particular component but are being pulled in due to package dependencies. I found a lot of such things (but not all, for sure)
- boolean type is missing

Beyond that I added a few more minor comments.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -planner-version | string | Sets the query planner version to use when generating the explain output. Valid values are V3 and Gen4 (default "V3") |
I assume Fallback is not supported by vtexplain?

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -ks-shard-map | string | JSON map of keyspace name -> shard name -> ShardReference object. The inner map is the same as the output of FindAllShardsInKeyspace (default "") |
```suggestion
| -ks-shard-map | string | JSON map of keyspace name -> shard name -> ShardReference object. The inner map should be the same as the output of FindAllShardsInKeyspace (default "") |
```

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtgate.md
> +| -alsologtostderr |  | log to standard error as well as files |
`boolean` seems to have disappeared from a bunch of places.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtgate.md
> +| -buffer_implementation | string | Allowed values: healthcheck (legacy implementation), keyspace_events (default) (default "keyspace_events") |
I think the previous sentence ("The algorithm....") is useful to keep.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtgate.md
> +| -catch-sigpipe |  | catch and ignore SIGPIPE on stdout and stderr if specified |
boolean

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtgate.md
> +| -disable_local_gateway |  | deprecated: if specified, this process will not route any queries to local tablets in the local cell |
we should delete this now (from the code).

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vttablet.md
> +| -allowed_tablet_types | value | Specifies the tablet types this vtgate is allowed to route queries to |
This should not be in vttablet flags, it's a vtgate flag.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -allowed_tablet_types | value | Specifies the tablet types this vtgate is allowed to route queries to |
Let's remove this, it's coming from healthcheck.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -db-credentials-vault-ttl | duration | How long to cache DB credentials from the Vault server (default 30m0s) |
technically these are all relevant only for vtgate but we currently have flag pollution because of the mysql package.
I think it's better to leave them out here.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -enable_query_plan_field_caching |  | This option fetches & caches fields (columns) when storing query plans (default true) |
This is a mess. I'd have expected all these flags to only be relevant to vtgate/vttablet.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -enable_replication_reporter |  | Use polling to track replication lag. |
should be only vttablet.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -enforce_strict_trans_tables |  | If true, vttablet requires MySQL to run with STRICT_TRANS_TABLES or STRICT_ALL_TABLES on. It is recommended to not turn this flag off. Otherwise MySQL may alter yo
These should be only vtgate, right?

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -heartbeat_enable |  | If true, vttablet records (if master) or checks (if replica) the current time of a replication heartbeat in the table _vt.heartbeat. The result is used to inform the serving
only vttablet.

2022-01-31 19:03 UTC, deepthi commented on content/en/docs/13.0/reference/programs/vtctld.md
> +| -allowed_tablet_types | value | Specifies the tablet types this vtgate is allowed to route queries to |
Let's remove this, it's coming from healthcheck.

2022-01-31 19:24 UTC, harshit-gangal commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -planner-version | string | Sets the query planner version to use when generating the explain output. Valid values are V3 and Gen4 (default "V3") |
the core planner remain same, so all the planner option should work.
I can still try and see.

2022-01-31 19:26 UTC, harshit-gangal commented
> Thank you for taking this on, it needed to be done. Did you generate these docs using a script? Two main points:
> 
> * Previously some options were edited out by hand because they are not actually relevant for the particular component but are being pulled in due to package dependencies. I found a lot of such things (but not all, for sure)
> * boolean type is missing
> 
> Beyond that I added a few more minor comments.

currently it is not done through script, but can be changed to do that, we can add a task for next release

2022-01-31 19:28 UTC, harshit-gangal commented
probably we have to think about how to place the flags in the packages so it does not show up where it is not used. for now, I will go through the comments and fix them here.

2022-02-01 04:58 UTC, harshit-gangal commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -planner-version | string | Sets the query planner version to use when generating the explain output. Valid values are V3 and Gen4 (default "V3") |
I checked the test and code. The test passed on setting to Gen4Fallback or other planner version but, on the vtexplain cmd if explicitly check them to be "v3" or "Gen4". I believe that check is not required. Will update this PR as per vtexplain command expects.

2022-02-02 21:01 UTC, kristee-planetscale requested changes, later dismissed
found some formatting and capitalization changes

2022-02-02 21:01 UTC, kristee-planetscale commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -shards | int     | Number of shards per keyspace. Passing -ks-shard-map/-ks-shard-map-file causes this flag to be ignored. (default 2)                                      |
Number of shards per keyspace. Passing -ks-shard-map/-ks-shard-map-file causes this flag to be ignored (default 2)

Removed period for formatting consistency

2022-02-02 21:01 UTC, kristee-planetscale commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -queryserver-config-passthrough-dmls | boolean | query server pass through all dml statements without rewriting (default false)
Query server pass through all dml statements without rewriting (default false)

Caps for consistency

2022-02-02 21:01 UTC, kristee-planetscale commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -ks-shard-map-file | string  | File containing json blob of keyspace name -> shard name -> ShardReference object (default "")                                                           |
File containing JSON blob of keyspace name -> shard name -> ShardReference object (default "")

Caps for consistency

2022-02-02 21:01 UTC, kristee-planetscale commented on content/en/docs/13.0/reference/programs/vtexplain.md
> +| -output-mode | string  | Output in human-friendly text or json (default "text")                                                                                                   |
Output in human-friendly text or JSON (default "text")

Caps for consistency

2022-02-10 23:05 UTC, hallaroo reviewed
I made changes to the branch to update vtctld.md, vtgate.md, and vttablet.md.

After the changes requested by Kristee I can approve.

One question: Should we also update the reference tables for v12 or v14?

2022-02-11 07:00 UTC, harshit-gangal commented
> I made changes to the branch to update vtctld.md, vtgate.md, and vttablet.md.
> 
> After the changes requested by Kristee I can approve.
> 
> One question: Should we also update the reference tables for v12 or v14?

we can definitely update for v14

2022-02-14 17:58 UTC, deepthi commented
> 
> One question: Should we also update the reference tables for v12 or v14?

Many of these are (I think) new in 13. Let us _not_ update v12 right now. If you find that some particular flag is missing from v12 docs we can do separate PRs for those.

2022-02-15 16:39 UTC, harshit-gangal commented
need approval for merge or @hallaroo are you planning to push changed to v14 doc as well?

2022-02-15 17:07 UTC, hallaroo commented
Hi I was planning on pushing the v14 docs today. 👍🏼  I can approve and merge as soon as I have that done this afternoon.

2022-02-15 22:16 UTC, hallaroo commented
The v14 docs are actually going to take me a bit to deal with. So I'll make my own new branch for v14 and request reviews once I'm ready.

2022-02-15 22:16 UTC, hallaroo approved these changes
LGTM

2022-02-15 22:16 UTC, merged