Add docs for the durability policies for release 14
vitessio/website pull request #968
Opened 2022-02-04 12:48 UTC by GuptaManan100

This PR copies changes to release 14 for the durability docs as done in https://github.com/vitessio/website/pull/955.
It also removes the `cross-cell` durability policy configuration since it isn't supported in Vitess yet.

2022-02-09 20:08 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> - - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This me
Now there are only 2? Line 18.
Maybe we should say that "There are 2 implementations supported in this release" or something like that.

2022-02-09 20:08 UTC, deepthi commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> - - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This me
Is everything following this section intentionally in bold? It looks like this
https://deploy-preview-968--vitess.netlify.app/docs/13.0/user-guides/configuration-basic/durability_policy/

2022-02-09 20:08 UTC, deepthi commented on content/en/docs/14.0/user-guides/configuration-basic/durability_policy.md
> +There are 3 implementations bundled with Vitess:
Same comments here as for the 13.0 version.

2022-02-10 08:10 UTC, GuptaManan100 commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> - - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This me
I see only `semi_sync` and `none` as bold. `(default)` is italicised

2022-02-10 08:12 UTC, GuptaManan100 commented on content/en/docs/14.0/user-guides/configuration-basic/durability_policy.md
> +There are 3 implementations bundled with Vitess:
Fixed this for both versions

2022-02-10 16:13 UTC, hallaroo commented on content/en/docs/14.0/user-guides/configuration-basic/durability_policy.md
> +{{< info >}}
I didn't catch this when the v13 docs went in but the formatting here for the code blocks looks really weird when done in an 'info' header.

It might be better to not have this last chunk of text in the {{< info >}} formatting. And it might be necessary to update the v13 doc as well.

2022-02-10 16:15 UTC, hallaroo requested changes
My only comment is on formatting as the code blocks don't look very good in the 'info' section:
<img width="861" alt="Screen Shot 2022-02-10 at 9 14 40 AM" src="https://user-images.githubusercontent.com/5854253/153449153-f593ad4d-80ac-4620-97df-f991f6a3bded.png">

2022-02-10 16:29 UTC, GuptaManan100 commented on content/en/docs/14.0/user-guides/configuration-basic/durability_policy.md
> +{{< info >}}
Fixed in both

2022-02-10 16:58 UTC, hallaroo commented on content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
> - - ***cross_cell*** - This durability policy sets the number of required semi-sync ACKers to 1. It only allows Primary and Replica type servers from a different cell to acknowledge semi sync. This me
In the preview everything is correctly formatted ... not sure why GitHub is showing a bold.

2022-02-10 16:59 UTC, hallaroo approved these changes
LGTM!

2022-02-10 17:00 UTC, merged

2022-02-10 18:24 UTC, deepthi commented
@GuptaManan100 after thoughts on this PR.
We do actually have 3 durability policy implementations, but cross_cell is supported only by vtorc, not PRS/ERS.
Is that correct?

2022-02-11 01:25 UTC, GuptaManan100 commented
`cross_cell` is supported by vtorc, but anytime someone calls any RPC like ChangeTabletType, StartReplication, etc, it will mess-up the semi-sync.