Expanding on Migrate documentation
vitessio/website pull request #990
Opened 2022-02-25 22:57 UTC by FancyFane

Signed-off-by: FancyFane <fane@planetscale.com>

This is a draft request for expanding the Vitess `Migrate` documentation. Once feedback is given, I can replicate these changes to the other versions of Vitess, and turn off the draft request.

2022-02-28 16:35 UTC, Anders-PlanetScale requested changes
I'm not intimately familiar with Migrate but the changes look good to me. My only nit-pick would be:

`* MoveTables erases the source data upon completion; Migrate keeps the source data intact.`
MoveTables has a flag -keep_data which will stop this behavior, so maybe say:

`* MoveTables, by default, erases the source data upon completion; Migrate keeps the source data intact.`
Or something like that?

2022-03-01 22:28 UTC, hallaroo requested changes
Couple of grammar things. I can approve once they are fixed.

2022-03-01 22:28 UTC, hallaroo commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +This command is built off of [MoveTables](../movetables) but has been extended to work with source and target topology services, and should be
This command is built off of [MoveTables](../movetables) but has been extended to work with source and target topology services. It should be

2022-03-01 22:28 UTC, hallaroo commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +Migrate has separate semantics and behaviors than MoveTables:
Migrate has separate semantics and behaviors from MoveTables:

2022-03-01 22:28 UTC, hallaroo commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +* MoveTables sets up routing rules and reverse replication, allowing for rollback prior to completion
MoveTables sets up routing rules and reverse replication, allowing for rollback prior to completion.

2022-03-01 22:28 UTC, hallaroo commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +    * SWitching traffic requires that the Target can create vreplication streams (in the \_vt database) on the Source database;
Switching traffic requires that the Target can create vreplication streams (in the \_vt database) on the Source database;

2022-03-01 22:28 UTC, hallaroo commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +      this may not be always possible on production systems.
this may not always be possible on production systems.

2022-03-01 23:26 UTC, FancyFane commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +    * SWitching traffic requires that the Target can create vreplication streams (in the \_vt database) on the Source database;
"that" in this bullet point maybe a filler word, so I've re-worded it further to remove it. 

```
Switching traffic requires the Target to have the ability to create vreplication streams (in the _vt database) on the Source; this may not always be possible on production systems.
```

2022-03-01 23:29 UTC, hallaroo commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +    * SWitching traffic requires that the Target can create vreplication streams (in the \_vt database) on the Source database;
Ah what I was correcting was the "SW" in "Switching". Anything else looks great to me lol

2022-03-01 23:37 UTC, FancyFane commented on content/en/docs/11.0/reference/vreplication/migrate.md
> +    * SWitching traffic requires that the Target can create vreplication streams (in the \_vt database) on the Source database;
Okay just double checking as that bullet point was modified further. Resolving this conflict and taking this out of draft mode.

2022-03-01 23:40 UTC, hallaroo approved these changes
lg;tm

2022-03-02 15:28 UTC, Anders-PlanetScale approved these changes
Looks good, thanks.

2022-03-02 15:29 UTC, merged