Update MySQL related version and recommendation info
vitessio/website pull request #993
Opened 2022-03-02 00:57 UTC by mattlord

H/T to @mreschke for pointing these out [here](https://github.com/vitessio/vitess/issues/9518#issuecomment-1055975374).

2022-03-30 15:50 UTC, dbussink approved these changes

2022-04-05 20:01 UTC, deepthi requested changes

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/11.0/get-started/local.md
> +version=13.0.0
Eh, we can't put v13 into v11 docs. I agree 6.0.20 is too old (unsupported by the time we got to v11), but this should be v11.

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/12.0/get-started/local.md
> +version=13.0.0
Similarly, v12 here.

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/13.0/get-started/local.md
> +version=13.0.0
👍

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/11.0/get-started/local.md
> +Download the [latest binary release](https://github.com/vitessio/vitess/releases) for Vitess on Linux. For example with Vitess 13:
13->11

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/12.0/get-started/local.md
> +Download the [latest binary release](https://github.com/vitessio/vitess/releases) for Vitess on Linux. For example with Vitess 13:
13->12

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/11.0/get-started/local.md
> +Vitess supports the databases listed [here](../../overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:
nit: I believe the semicolon at the end should be a period.
Same in all 4 docs.

2022-04-05 20:01 UTC, deepthi commented on content/en/docs/11.0/get-started/local.md
> +Vitess supports the databases listed [here](../../overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:
@sougou are we ready to officially recommend 8.0?

2022-04-05 20:04 UTC, deepthi commented on content/en/docs/11.0/user-guides/configuration-basic/planning.md
> +1. [TopoServer](../../../concepts/topology-service/): This is the server in which Vitess stores its metadata. We recommend Etcd if you have no other preference.
nit: Etcd -> etcd. The project name is all lowercase in their docs. This applies to all 4 places where this changed in this PR.

2022-04-05 20:10 UTC, sougou commented on content/en/docs/11.0/get-started/local.md
> +Vitess supports the databases listed [here](../../overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:
> @sougou are we ready to officially recommend 8.0?

Yeah. I think we have enough mileage on 8.0 to recommend it.

2022-04-11 21:00 UTC, mattlord commented on content/en/docs/11.0/get-started/local.md
> +Vitess supports the databases listed [here](../../overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:
What follows are examples of installing MySQL 8 in common distros so I believe the colon was intentional (I I didn't change that), but I don't feel strongly.

2022-04-11 21:44 UTC, mattlord commented
Thank you for the review @deepthi ! I've also [incorporated changes related to the tentatively planned MariaDB support EOL in 14.0](https://github.com/vitessio/website/pull/993/commits/aceabf7dcbdfa28d9ff158c612de94f8faab40a1). So I will hold off on merging this until that final decision is made — likely in the next month or so I think, barring any new information or details coming to light in the RFC. Or if you would prefer to keep them separate then I can revert [the commit that included those changes](https://github.com/vitessio/website/pull/993/commits/aceabf7dcbdfa28d9ff158c612de94f8faab40a1) and deal with that part later.

2022-05-24 20:08 UTC, deepthi commented on content/en/docs/11.0/get-started/local.md
> +Vitess supports the databases listed [here](../../overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:
Not obvious, but fine I guess :)

2022-05-24 20:08 UTC, deepthi approved these changes

2022-06-06 20:52 UTC, merged